### ISSUE TITLE
Add a visual indicator when an EC2 instance is terminated

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#121]
When terminating an instance in the EC2 resources tab, we need to somehow let the user know that a request has been sent since the removal takes a bit of time. Using a material UI [snackbar component](https://material-ui.com/demos/snackbars/) is probably a good solution to inform the user.

**Comment by mike44441** [comment]
I would be interested in implementing this feature. If you have any advise, it would be very much appreciated!

**Comment by helfi92** [comment]
Definitely! I think the [snackbar component](https://material-ui.com/demos/snackbars/) is the way to go. Try importing it and see if you can render the snackbar with a message at the bottom of the screen. Once that's done, you can simply make sure that function is called when the user terminates one or all of the EC2 resources. Let me know if you have any questions :)

**Comment by mike44441** [comment]
If you have any feedback on this, let me know!

**Comment by helfi92** [comment]
A screenshot would be helpful :)

**Comment by mike44441** [comment]
Hello, sorry about the late response. But when I was trying to test and lost my authentication, I am a little confused about this part in trying to get it to work again. I know that I have to get taskcluster-cli. I was wondering if there was some other login credentials, by default that are usable to be able to see the EC2 resources.

**Comment by helfi92** [comment]
All you need is taskcluster-CLI and the required scopes. Once you are logged in, there will be an error panel saying which scopes (permissions) are needed. You can show me a screenshot of the error and I will make sure you have those permissions :)

**Comment by mike44441** [comment]
Alright, the error I am getting when trying to see the error is
![screen shot 2018-10-04 at 12 31 05 pm](https://user-images.githubusercontent.com/23268239/46498159-7a5fef80-c7d1-11e8-8c2d-0185ab0be540.png)

**Comment by helfi92** [comment]
Bad mac most probably means you are not properly authenticated. I see that you are logged in via Github. You should use Taskcluster CLI to log in. Next step would be to logout and login with manual credentials where you will get the client ID and access token from the Taskcluster CLI.

**Comment by mike44441** [comment]
Would this be from the part in the web-server section involving using the taskcluster-cli to create a user and key? Because I am still unable to use the taskcluster in the command prompt after following the instruction and not having errors on the make.

**Comment by mike44441** [comment]
<img width="697" alt="screen shot 2018-10-04 at 1 06 36 pm" src="https://user-images.githubusercontent.com/23268239/46499932-5b179100-c7d6-11e8-93b0-1681ef5f79a7.png">

**Comment by helfi92** [comment]
If you're developing for taskcluster-cli then you'll need to use `go`. However, you'll only the program (not building for it). You'll have to download the binary from https://github.com/taskcluster/taskcluster-cli#installation and run it.

**Comment by mike44441** [comment]
Alright, I have been trying to do that on my Mac, but for some reason it won't run allow me to run the binaries. That's why I was trying through the go method before.

**Comment by mike44441** [comment]
Yes I did, which makes this more confusing, and I am recommended to use a unarchiver on it still after doing that.

**Comment by helfi92** [comment]
What happens when you try to run the file via the terminal?

```
./<binary-name>
```

**Comment by mike44441** [comment]
This solution worked! But the problem now is, I assumed that this would create the path, and this does not seem to be the case, is there a path that I need to export for this as well that wasn't stated in the installation?

**Comment by helfi92** [comment]
> I assumed that this would create the path

I'm not sure I understand what you mean here. Could you elaborate, please?

You need to do `./<binary-name> signin`. This would open a browser to log you in. Once logged in, the terminal will output your credentials.

**Comment by mike44441** [comment]
Awesome that did the job, but when looking at the login id, which sections belong to the Client_id and access token?

**Comment by helfi92** [comment]
What do you see in the terminal after you login?

`TASKCLUSTER_CLIENT_ID` belongs to the client id.
`TASKCLUSTER_ACCESS_TOKEN` belongs to the access token.

**Comment by mike44441** [comment]
Credentials output as environment variables
mozilla-auth0/github|23268239|mike44441/taskcluster-web-server

**Comment by helfi92** [comment]
Right. Now you can open http://localhost:5080/aws-provisioner/gecko-t-linux-xlarge and click on "Sign In" from the left panel and click on "Sign In with credentials". Paste your client ID and access token there.

**Comment by mike44441** [comment]
SO my question is in the long line is the first section up to the first bar ( | ) The id and the token is the numerical values. If this is the case, I have tried this already and when I input it I get
![screen shot 2018-10-05 at 10 37 10 am](https://user-images.githubusercontent.com/23268239/46550693-a3908680-c88a-11e8-8b40-c5a2595e7665.png)

**Comment by helfi92** [comment]
The client ID you seem to be logged in as is set to `mozilla-auth0/github`. Correct me if I'm wrong but your terminal output had `mozilla-auth0/github|23268239|mike44441/taskcluster-web-server` as the client ID. Is there a reason for the difference? It should be:

![screen shot 2018-10-05 at 1 39 41 pm](https://user-images.githubusercontent.com/3766511/46550833-2a059200-c8a4-11e8-82b7-210ae54db696.png)

**Comment by mike44441** [comment]
I was not given or could not find the access token.

**Comment by helfi92** [comment]
Do you see something different?

```bash
> ./taskcluster signin
Starting
Listening for a callback on: http://localhost:63410
Opening URL: https://tools.taskcluster.net/auth/clients/new?name=cli&description=Temporary+client+for+use+on+the+command+line&scope=%2A&expires=1d&callback_url=http%3A%2F%2Flocalhost%3A63410
export TASKCLUSTER_CLIENT_ID='mozilla-auth0/ad|Mozilla-LDAP|haali/cli'
export TASKCLUSTER_ACCESS_TOKEN='xxx'
Credentials output as environment variables
```

Could you show me a screenshot, please?

**Comment by mike44441** [comment]
<img width="697" alt="screen shot 2018-10-05 at 10 49 58 am" src="https://user-images.githubusercontent.com/23268239/46551386-7c3ab900-c88c-11e8-9a31-e75a1ac12531.png">

**Comment by helfi92** [comment]
OK good:

`Opening URL: https://tools.taskcluster.net/auth/clients/new?name=cli&description=Temporary+client+for+use+on+the+command+line&scope=%2A&expires=1d&callback_url=http%3A%2F%2Flocalhost%3A63410` should have opened a new browser tab/window. Do you see that?

**Comment by mike44441** [comment]
Yeah, I put this exact command before and was not directed to this before. I had tried several times, but now it seems to be working then and I was able to log into the site and create the cli id now.
![screen shot 2018-10-05 at 10 55 41 am](https://user-images.githubusercontent.com/23268239/46551689-40ecba00-c88d-11e8-9ace-f4c4169f5c17.png)

**Comment by helfi92** [comment]
Try refreshing your page. Does the error go away?

**Comment by mike44441** [comment]
![screen shot 2018-10-05 at 10 59 59 am](https://user-images.githubusercontent.com/23268239/46551893-d0926880-c88d-11e8-8651-e5846edcf059.png)

**Comment by helfi92** [comment]
Could you try restarting the `taskcluster-web-server` process.

**Comment by mike44441** [comment]
I still get the same errors

**Comment by helfi92** [comment]
If you do `git log --oneline -n 1` in the `taskcluster-web-server`, what do you see?

**Comment by mike44441** [comment]
<img width="1082" alt="screen shot 2018-10-05 at 11 15 43 am" src="https://user-images.githubusercontent.com/23268239/46552593-033d6080-c890-11e8-8f18-d6abdde12cdd.png">

**Comment by helfi92** [comment]
Interesting. You can try `rm -rf node_modules && rm -rf build && yarn && yarn start` inside `taskcluster-web-server` and see if that works.

**Comment by mike44441** [comment]
Hey so I am trying to test the snack bar, but I get this error when I try to terminate individual tasks
![screen shot 2018-10-05 at 12 27 18 pm](https://user-images.githubusercontent.com/23268239/46556006-17865b00-c89a-11e8-847e-f0afd03df1ec.png)

And when I do terminate all I get
![screen shot 2018-10-05 at 12 28 24 pm](https://user-images.githubusercontent.com/23268239/46556031-3258cf80-c89a-11e8-853d-95e9e2f49d91.png)

**Comment by helfi92** [comment]
Step number one would be to be able to display a snackbar with a message. Once that's done, we can hook it up to the terminate buttons. To test the snackbar, create a dummy button that would trigger the snackbar upon clicking on the button.

**Comment by mike44441** [comment]
I have been trying to generate a Snackbar when handling the terminate instance. But, I still can't get it to work and I think I will need permissions again to be able to see AWS Provisioner. I have coding, but I am unsure where I should try to insert the snackbar feature. Should I be trying to to this in 
.../GitHub/taskcluster-web/src/views/AwsProvisioner/ViewWorkerType or
.../GitHub/taskcluster-web/src/components/Ec2ResourcesTable

**Comment by helfi92** [comment]
I think it makes sense to put it under `.../GitHub/taskcluster-web/src/views/AwsProvisioner/ViewWorkerType/index.jsx`. Regarding permissions, you'll have to show me what kind of error you're getting so I could provide you with the relevant scopes (permissions).

**Comment by helfi92** [comment]
Now that we have [migrated to material UI v3](https://github.com/taskcluster/taskcluster-web/commit/0a187e352bf6eb97c60682ba69b4004dd5cba632#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R18), many bugs in the [`Snackbar`](https://material-ui.com/demos/snackbars/) component have been fixed.
