### ISSUE TITLE
Add a Cache Purges entry to the navigation drawer

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#122]
The navigation drawer doesn't seem to have an entry to Cache Purges. Let's add it.

![screen shot 2018-09-18 at 12 52 16 pm](https://user-images.githubusercontent.com/3766511/45703274-d6741400-bb41-11e8-87dc-8d9d2157eac1.png)

**Comment by mike44441** [comment]
Hello! This is my first time working on something like this and would like to contribute.

**Comment by helfi92** [comment]
Welcome @mike44441 :) The first step is to have your local setup running by going over the [README](https://github.com/taskcluster/taskcluster-web/blob/master/README.md). Once that's done, you'll be able to add a Cache Purges entry in the navigation drawer. Let me know if you get stuck somewhere.

**Comment by mike44441** [comment]
Alright I have a question about picking the icon at the moment. Based on the other elements in the list, is there a specific one you would like or should I just place something as a filler for the time being in both the import and the list element?

**Comment by helfi92** [comment]
Feel free to pick any icon for now. We can change it later once you send a pull-request :)

**Comment by helfi92** [comment]
Completed in https://github.com/taskcluster/taskcluster-web/commit/0be756e920df625c36c14a81c07f151a9740d712.
