### ISSUE TITLE
Clicking on Interactive should parameterize the task

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#126]
![screen shot 2018-09-20 at 3 16 27 pm](https://user-images.githubusercontent.com/3766511/45841558-2db3e900-bce8-11e8-9d55-9f7a26419709.png).

**Comment by helfi92** [comment]
@Mryashbhardwaj How do you feel about https://github.com/taskcluster/taskcluster-web/issues/178. I think this issue might be confusing to tackle.

**Comment by Mryashbhardwaj** [comment]
@helfi92 , sure.

**Comment by helfi92** [comment]
Not an issue anymore.
