### ISSUE TITLE
Enhance the reset access token experience

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#139]
It would be great to add a way to quickly copy the access token. This would probably mean moving away from the ErrorPanel component and using something else.

![screen shot 2018-10-02 at 3 12 52 pm](https://user-images.githubusercontent.com/3766511/46371635-e0743780-c656-11e8-8f65-fd94d3c87834.png)

**Comment by vaishnavipamulapati** [comment]
I'd like to take this issue

**Comment by helfi92** [comment]
It's yours!
