### ISSUE TITLE
More precision in time duration

### ISSUE THREAD

**Issue by SimonSapin** [taskcluster/taskcluster-web#141]
In some places of the web UI, time durations are displayed in a human-readable way. For example https://tools.taskcluster.net/groups/PSGMYtDUSji_qGHQ_mLt9Q/tasks/fNN7HLfYRJy1FIh3lS90zQ/runs/0 right now shows “Resolved | 31 minutes ago (an hour later)”

This is nice, much easier than mentally substracting 2018-10-03T07:29:54.370Z from 2018-10-03T08:15:37.386Z. However it’s also really inaccurate! The duration is actually much closer to 46 minutes than an hour. Some approximation is good for human readability, but a +30% error is hard to swallow.

Could this formatting be configured to keep at least two significant digits?

----

Aside: how long tasks take to run matters for Servo because we only merge a pull request after it has been tested, and we merge exactly the commit that has been tested. Unless we add speculation about the test results of previous PRs, this requires us to keep a queue of PRs and only test one of them at a time. Sometimes the queue grows, so cutting 15 minutes from the cycle time is significant.

**Comment by helfi92** [comment]
`moment.js` is used in [taskcluster-tools](https://github.com/taskcluster/taskcluster-tools) to determine dates. This is the breakdown of what will be displayed:

![screen shot 2018-10-03 at 7 49 59 am](https://user-images.githubusercontent.com/3766511/46408778-43aaac00-c6e1-11e8-87d7-52b540b7ddbf.png)

In taskcluster-web (not yet published), we use `date-fns` but they seem to use a similar breakdown:

![screen shot 2018-10-03 at 7 54 05 am](https://user-images.githubusercontent.com/3766511/46408873-95533680-c6e1-11e8-8c97-9c56e2f21313.png)

I've opened https://github.com/date-fns/date-fns/issues/908 to get more information about customizing the breakdown.

**Comment by SimonSapin** [comment]
Thanks!

**Comment by fiennyangeln** [comment]
@helfi92 How about using this method? https://date-fns.org/v1.29.0/docs/distanceInWordsStrict

**Comment by helfi92** [comment]
ooooo nice find! I'll integrate that. Thank you @fiennyangeln.

**Comment by helfi92** [comment]
Taskcluster web now shows more accurate time durations:

_Example: Resolved 57 minutes ago_

![screen shot 2018-10-05 at 9 00 52 am](https://user-images.githubusercontent.com/3766511/46536697-45a97200-c87d-11e8-927b-21e43bd2ac9b.png)
