### ISSUE TITLE
Fix icon size

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#162]
Navigate to a task view (e.g., http://localhost:5080/tasks/ddY5vj6fT8uEM99fma7t5g). The "Source" link icon is smaller than the other icons. Let's fix that.

<img width="524" alt="screen shot 2018-10-13 at 7 35 21 pm" src="https://user-images.githubusercontent.com/3766511/46911054-69288880-cf1f-11e8-97af-949bcd67dca1.png">

**Comment by Ark20** [comment]
I'd like to claim this issue but. I cloned this repo, installed the dependencies and ran npm start but got an error: `Cannot read property 'includes' of undefined`. Is there anything else I need to do, to run the app? @helfi92

**Comment by helfi92** [comment]
Do you have a `.env` file defined in the directory? Something like:

```bash
APPLICATION_NAME="Taskcluster"
PORT="5080"
```

Also, try using `yarn` instead of `npm`:

```bash
yarn
yarn start
```

`yarn` will install the dependencies and `yarn start` is basically `npm run start`.

Does this fix your issue? If not, make sure you have [`taskcluster-web-server`](https://github.com/taskcluster/taskcluster-web-server) running in a separate terminal. Hopefully that helps.

**Comment by Ark20** [comment]
Thank you! I got the web server to run but and created a .env file but I'm getting the same result. Should the `.env` be in the root of the directory?

**Comment by BinSquare** [comment]
> Thank you! I got the web server to run but and created a .env file but I'm getting the same result. Should the `.env` be in the root of the directory?

Yup! More detail is in the readme - environment section of this project. Good luck

**Comment by Mryashbhardwaj** [comment]
Hi , can i pick this up ?

**Comment by Ark20** [comment]
Thank You @BinSquare I'm going to take a look now!

**Comment by helfi92** [comment]
Hi @Mryashbhardwaj, this is probably because you don't have [`taskcluster-web-server`](https://github.com/taskcluster/taskcluster-web-server) running on a separate terminal. Btw, this issue is assigned to @Ark20. Let me know if you want to try tackling something else like https://github.com/taskcluster/taskcluster-web/issues/163 :)

**Comment by Ark20** [comment]
Hey @helfi92 I've gotten the server to run in another terminal and added the .env as suggested in the `.readme` but I'm getting this error.
<img width="1436" alt="screen shot 2018-10-14 at 10 04 35 am" src="https://user-images.githubusercontent.com/20876942/46919751-a4b36900-cf98-11e8-8191-d192a86cfc93.png">

**Comment by Mryashbhardwaj** [comment]
Hi , can i pick this up ?

> Hi @Mryashbhardwaj, this is probably because you don't have [`taskcluster-web-server`](https://github.com/taskcluster/taskcluster-web-server) running on a separate terminal. Btw, this issue is assigned to @Ark20. Let me know if you want to try tackling something else like #163 :)

i do have the server running on a diffrent terminal, 
i did not found anybody named under the assigned section . i have raised a pull request too.

**Comment by helfi92** [comment]
@Ark20 This works but if we do that we will lose the styling done by `classes.sourceHeadline`. Try this:

```diff
diff --git a/src/components/TaskDetailsCard/index.jsx b/src/components/TaskDetailsCard/index.jsx
index d05243f..4ff0460 100644
--- a/src/components/TaskDetailsCard/index.jsx
+++ b/src/components/TaskDetailsCard/index.jsx
@@ -38,6 +38,9 @@ import { task } from '../../utils/prop-types';
     textOverflow: 'ellipsis',
     overflowX: 'hidden',
   },
+  sourceHeadlineText: {
+    flex: 1,
+  },
   listItemButton: {
     ...theme.mixins.listItemButton,
   },
@@ -108,6 +111,7 @@ export default class TaskDetailsCard extends Component {
                 target={isExternal ? '_blank' : null}
                 rel={isExternal ? 'noopener noreferrer' : null}>
                 <ListItemText
+                  className={classes.sourceHeadlineText}
                   classes={{ secondary: classes.sourceHeadline }}
                   primary="Source"
                   secondary={task.metadata.source}
```
