### ISSUE TITLE
Add copy to clipboard feature

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#163]
Steps to reproduce:

1. Navigate to http://localhost:5080/tasks/Aia7BIyvRGexdGaoeqT8NA
2. Click on the "Created" row

<img width="1146" alt="screen shot 2018-10-14 at 11 48 01 am" src="https://user-images.githubusercontent.com/3766511/46919040-172b4580-cfa7-11e8-9add-864d5c2fb81c.png">

Expected: The date time is copied to the clipboard
Current: The date time not copied to the clipboard

**Comment by Mryashbhardwaj** [comment]
> http://localhost:5080/tasks/Aia7BIyvRGexdGaoeqT8NA

the link here is specific to the tasks that you have added in you local , right ?
for me to be able to replicate , would  i have to add my own tasks ?

**Comment by helfi92** [comment]
You should be able to view this task without having to create your own task. If you're not able to view the task, let me know what kind of error you are seeing and I'll try to help.

**Comment by Mryashbhardwaj** [comment]
https://github.com/taskcluster/taskcluster-web/issues/162#issuecomment-429630548

this is the error i see when i try to open that link . 
Note : i am logged in using some random values when this error came .
the client taskcluster-web and taskcluster-web-server are able to comunicate as i can see 
> https://paste.fedoraproject.org/paste/PsftxFEzycg9hwzFhXw1jQ
on the server terminal.

also i get  a diffrent erro when i sign out .

![2018-10-15-010915_1209x750_scrot](https://user-images.githubusercontent.com/13954513/46921283-277b0900-d017-11e8-83c0-b29dd6ca9aea.png)

server terminal output:
> https://paste.fedoraproject.org/paste/wcOUWfRedcqx~BQb7yiu4A

also , following is my .env file 

> APPLICATION_NAME="Taskcluster"
> AUTH0_DOMAIN="auth.mozilla.auth0.com"
> AUTH0_CLIENT_ID="29t2n3LKKnyTbGtWmfTkQpau0mp7QmMH"
> AUTH0_REDIRECT_URI="http://localhost:5080/login"
> AUTH0_RESPONSE_TYPE="token id_token"
> AUTH0_SCOPE="openid profile"
> TASKCLUSTER_ROOT_URL="http://localhost:3050"
> LOGIN_STRATEGIES=""
> PORT="5080"

**Comment by helfi92** [comment]
Hm, try doing `git diff` to see if you changed anything by accident in `taskcluster-web-server`. In the server, the only thing that should be changed is `user-config.yml`. It should be:

```bash
defaults:
  taskcluster:
    rootUrl: https://taskcluster.net
```

**Comment by Mryashbhardwaj** [comment]
Yeah , that worked .
What exactly should be cppied to the clipboard . I am asuming "13 hours ago" (in the given case).

I noticed that none of the copy icons are working.

**Comment by helfi92** [comment]
> What exactly should be cppied to the clipboard . I am asuming "13 hours ago" (in the given case).

The raw data will be in the form `2018-10-15T12:07:34.946Z`. We actually transform the data to say something like `13 hours ago` to make it more readable. When the user clicks the copy icon, we want to copy the raw data.

> I noticed that none of the copy icons are working.

That's right. First I would open a pull-request for one copy icon. Once we agree on how it should be implemented, we could add the logic to the rest of the copy icons.

**Comment by gurjotsingh4398** [comment]
@helfi92 Can I work on this issue?

**Comment by helfi92** [comment]
@gurjotsingh4398 I think @Mryashbhardwaj is working on this issue. Let me know if you want to tackle https://github.com/taskcluster/taskcluster-web/issues/159.

**Comment by gurjotsingh4398** [comment]
@helfi92 Ya of course I would like to try.

**Comment by helfi92** [comment]
Awesome, let's continue our chat in #159.

**Comment by helfi92** [comment]
@Mryashbhardwaj How is it going? Feel free to use https://github.com/nkbt/react-copy-to-clipboard for copying to the clipboard.

**Comment by Mryashbhardwaj** [comment]
@helfi92 , I have made a pull request but I see the following issue 

> https://travis-ci.org/taskcluster/taskcluster-web/builds/443135489?utm_source=github_status&utm_medium=notification

i guess this is because  i anstaled a new package , and the yarn lock file cant be updated?
am i right ? how do i fix ?

**Comment by helfi92** [comment]
Try removing the `yarn.lock` file with `rm yarn.lock` and the regenerating it with `yarn`. Before you do however, I recommend you pull the latest changes from master.

**Comment by helfi92** [comment]
> I have a confusion regarding the "Deadline" tag, What should i copy {task.deadline + task.created} or {task.deadline} or what.

Good question. When you see `<DateDistance from={} offset={} />` you can copy whatever is inside `from`. To answer your question, copy `{task.deadline}`.

>  Also Should i extend the copy functionality to the "Tasks Run" Component also ?

Yes, you can extend the copy functionality to all views that have that copy icon.

```bash
➜  grep -r --exclude-dir node_modules "ContentCopyIcon" .
./src/components/TaskDetailsCard/index.jsx:import ContentCopyIcon from 'mdi-react/ContentCopyIcon';
./src/components/TaskDetailsCard/index.jsx:                <ContentCopyIcon />
./src/components/TaskDetailsCard/index.jsx:                <ContentCopyIcon />
./src/components/TaskDetailsCard/index.jsx:                <ContentCopyIcon />
./src/components/WorkerTable/index.jsx:import ContentCopyIcon from 'mdi-react/ContentCopyIcon';
./src/components/WorkerTable/index.jsx:                <ContentCopyIcon size={iconSize} />
./src/components/WorkerTable/index.jsx:                  <ContentCopyIcon size={iconSize} />
./src/components/WorkerTypesTable/index.jsx:import ContentCopyIcon from 'mdi-react/ContentCopyIcon';
./src/components/WorkerTypesTable/index.jsx:                  <ContentCopyIcon size={iconSize} />
./src/components/TaskRunsCard/index.jsx:import ContentCopyIcon from 'mdi-react/ContentCopyIcon';
./src/components/TaskRunsCard/index.jsx:                <ContentCopyIcon />
./src/components/TaskRunsCard/index.jsx:                <ContentCopyIcon />
./src/components/TaskRunsCard/index.jsx:                <ContentCopyIcon />
./src/components/TaskRunsCard/index.jsx:                <ContentCopyIcon />
./src/components/WorkersTable/index.jsx:import ContentCopyIcon from 'mdi-react/ContentCopyIcon';
./src/components/WorkersTable/index.jsx:                <ContentCopyIcon size={iconSize} />
./src/components/WorkersTable/index.jsx:                  <ContentCopyIcon size={iconSize} />
./src/components/WorkersTable/index.jsx:                <ContentCopyIcon size={iconSize} />
```

**Comment by Mryashbhardwaj** [comment]
I have submitted a pull request [ #177](https://github.com/taskcluster/taskcluster-web/pull/177).

**Comment by Mryashbhardwaj** [comment]
@helfi92 , what should i work on next. And where should i ask you such questions ?
