### ISSUE TITLE
Create a customized snackbar component 

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#178]
We will need to use a [customized snackbar](https://material-ui.com/demos/snackbars/#customized-snackbars) component to give feedback to users. Let's create a component in `src/component/Snackbar` capable of doing that.

The props of the component:

* `variant`: One of `error`, `warning`, `info`, and `success`. The variant will affect the background color of the Snackbar as well as add an icon from [`mdi-react`](https://materialdesignicons.com/).
* `message`: `string`.

Any other prop fed to `src/components/Snackbar` should be fed to material-ui's Snackbar component.

For inspiration, you can look at https://github.com/taskcluster/taskcluster-web/blob/master/src/components/Button/index.jsx.

**Comment by helfi92** [comment]
@Mryashbhardwaj Do you want to work on this issue? :)

**Comment by Mryashbhardwaj** [comment]
Yeah, Sure :)

**Comment by helfi92** [comment]
Awesome, feel free to ask questions or let me know if I've been unclear in the issue description.

**Comment by Mryashbhardwaj** [comment]
@helfi92 , i dont have good understanding of how react works. Is it fine if i first get some clarity on React and then get on with this. What do you suggest ?

**Comment by helfi92** [comment]
Definitely. Just to give you an idea of how it will end up:

```jsx
import React, { Component } from 'react';
import { string, oneOf } from 'prop-types';
import MuiSnackbar from '@material-ui/core/Snackbar';
import { withStyles } from '@material-ui/core/styles';

@withStyles(theme => ({
  // styles here can be access via this.props.classes
});
export default class Snackbar extends Component {
  static propTypes = {
    variant: oneOf(['success', 'info', 'error', 'warning']),
    message: string.isRequired,
  };

  static defaultProps = {
    variant: 'success',
  };

  render() {
    const { classes, variant, message, ...props } = this.props;

    // ...
  }
}

```

**Comment by Mryashbhardwaj** [comment]
Thanks for the snippet, Just give me some time to brush up on React so that i can code with more confidence. Thanks a lot for support and guidance.  :)

**Comment by helfi92** [comment]
@Mryashbhardwaj Would you be interested in tackling https://bugzilla.mozilla.org/show_bug.cgi?id=1455130? It's a backend bug :) If you are, then please comment on the bug there and we can take it from there.
