### ISSUE TITLE
Remove `staticContext` error from console

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#179]
Navigate to http://localhost:5080/provisioners. Open devtools to look at the console. There is an error in the console about `staticContext`:

![screen shot 2018-10-19 at 2 50 31 pm](https://user-images.githubusercontent.com/3766511/47237890-5e9e4100-d3ae-11e8-8a02-21bfd5a1777c.png)

To fix this issue, a similar fix to https://github.com/taskcluster/taskcluster-web/blob/e035521b680396907ece04680587ad1d18a3f5c7/src/components/RouteWithProps/index.jsx#L29 should be implemented. Your task is to figure out where. Here's more information about the issue: https://github.com/taskcluster/taskcluster-web/pull/167#discussion_r226274280.

**Comment by mash-a** [comment]
I would like to work on this issue.

**Comment by helfi92** [comment]
Awesome! Go for it.

**Comment by peterr101** [comment]
Hi, I am new to open source, but would like to contribute on this issue if possible?

**Comment by helfi92** [comment]
Hi @peterr101, I believe @mash-a is working on that issue. How is it going @mash-a?

**Comment by mash-a** [comment]
@helfi92 I figured out where the issue is coming from, I was just having some issues with eslint.

**Comment by helfi92** [comment]
Can I help :) ? You can try `yarn lint --fix` to fix issues.

**Comment by helfi92** [comment]
Ah, we should probably display a better error. Create a `.env` file in the root directory and define `TASKCLUSTER_ROOT_URL`. See the [README section](https://github.com/taskcluster/taskcluster-web#environment). Let me know if that fixes it.

**Comment by mash-a** [comment]
Yup that fixed it! Thank you :)
