### ISSUE TITLE
Task actions

### ISSUE THREAD

**Issue by eliperelman** [taskcluster/taskcluster-web#19]
This is synonymous with the task actions you can take at https://tools.taskcluster.net/groups/e4MvyI2FSjqEmLjZ1mUbYw/tasks/S02Aav_PSJOvbQSopKYVyw/details

<img width="409" alt="screen shot 2018-04-10 at 11 42 06 am" src="https://user-images.githubusercontent.com/285899/38570784-4416062e-3cb4-11e8-845e-ea8a729d4595.png">

My initial instinct is to use a speed dial here, although I'm not sure how that's going to look with 14 different actions. We may resort to a drop-up instead with a FAB. We may also consider dropping actions that can't be taken, e.g. disabled actions.

**Comment by helfi92** [comment]
These actions should be split between the group and task view.
