### ISSUE TITLE
Fix dialog error

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#193]
Steps to reproduce:

1. Navigate to http://localhost:5080/. If you were previously logged in, log out.
2. Open dev-tools
3. Click on "Sign In"
4. Click on "Sign in with credentials"
5. Click anywhere outside the dialog

Actual:
<img width="1677" alt="screen shot 2018-10-23 at 12 03 28 pm" src="https://user-images.githubusercontent.com/3766511/47374324-b1803d00-d6bb-11e8-8dc5-75bdaf2a967d.png">

Expected: No error

**Comment by Saumya29** [comment]
I would like to work on this issue.

**Comment by helfi92** [comment]
@Saumya29 Go for it.

**Comment by helfi92** [comment]
I can't seem to replicate the issue anymore. It must have been accidentally fixed in https://github.com/taskcluster/taskcluster-web/commit/2c64f3f8b44c1d7113ded5b59503d4f14d0646c3. Thank you @Saumya29 for offering your help :)
