### ISSUE TITLE
Restructure the Landing page to include the navigation bar

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#196]
Actual: Navigating to `localhost:5080` when logged out shows:

![screen shot 2018-10-23 at 1 59 12 pm](https://user-images.githubusercontent.com/3766511/47380622-ded4e700-d6cb-11e8-86b4-33c5b94a7854.png)

Expected: It should include the navigation bar that we usually see when logged in. Something like:

![screen shot 2018-10-23 at 1 57 50 pm](https://user-images.githubusercontent.com/3766511/47380567-c95fbd00-d6cb-11e8-9f9c-b1cb0dc22e3c.png)

**Comment by projectyang** [comment]
I'd like to take this issue. :)

**Comment by helfi92** [comment]
Go for it :) Looking forward to seeing what you come up with!
