### ISSUE TITLE
Username should be smaller

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-web#199]
![screenshot_2018-10-23 taskcluster](https://user-images.githubusercontent.com/28673/47382190-b353fb80-d6cf-11e8-9c27-9d3d219ac406.png)

That's a lot of wrapping!  When we have users logging in with non-manual credentials, it will be shorter (e.g., "Dustin Mitchell") but it would be nice to display this form more succinctly.

**Comment by Abhiraj-Tulsyan** [comment]
I am completely new to open source and contributions. I want to take this issue and solve it

**Comment by Abhiraj-Tulsyan** [comment]
Thank you sir.Do I need to clone only this repo or any other repo as well
for making it work and running locally

**Comment by helfi92** [comment]
The [README](https://github.com/taskcluster/taskcluster-web) should have all of the information to get you running. Yes, you'll need to have `taskcluster-web-server` running in a second terminal as explained in the README.

> Do I need to clone only this repo

You should probably consider forking first then cloning your own fork.

**Comment by sammysamx20** [comment]
I am willing to do this!

**Comment by helfi92** [comment]
@sammysamx20 This issue is assigned to @Abhiraj-Tulsyan for now. Do you want to tackle https://github.com/taskcluster/taskcluster-web/issues/221 instead? I'd be happy to mentor.

**Comment by sammysamx20** [comment]
@helfi92 Sure I'll be willing to try that one!

**Comment by Abhiraj-Tulsyan** [comment]
@helfi92 <https://github.com/helfi92>
Hello sir,
Help needed.I am very new to web development and know nothing of react and
bunch of different things included there.But I still wanna solve this
problem.
All I could trace is that the part of the html was in
src/components/dashboard/usermenu.jsx But I can't figure out the flow of
the app . Could you please guide me a little bit

**Comment by sammysamx20** [comment]
Hey I had a similar issue too with working with the app don’t worry! You should be able to do some inline React js styling for that. What I would do is
Find the component/html element that holds username. 
Give it a style prop like <h1 style={usernamestyle}></h1> 
Then make a const usernamestyle variable in scope and set it equal to the desired text size fontSize=“12” or whatever.

**Comment by djmitche** [comment]
Props to Sam for helping out!

**Comment by eliperelman** [comment]
@djmitche did you just say "props" in a react repo? 😂

**Comment by djmitche** [comment]
Wow, you "rendered" judgment on my choice of words very quickly!

**Comment by eliperelman** [comment]
The "state" of this issue is quickly devolving.

**Comment by Abhiraj-Tulsyan** [comment]
@helfi92 @djmitche 
Hello sir
![image](https://user-images.githubusercontent.com/31121715/47583589-8e80b200-d975-11e8-84c0-48df5f46346d.png)

See if this is the desired solution or not

**Comment by ankur01oct** [comment]
Hi , 
I want to work on the issue

**Comment by helfi92** [comment]
Fixed in https://github.com/taskcluster/taskcluster-web/commit/bf85f6a90e4d3c7ca8c1db607dd8a47492bb03bb and https://github.com/taskcluster/taskcluster-web/commit/046bc3883d6b190461a7f69617e457ca6767c0dd.

<img width="240" alt="screen shot 2018-10-28 at 9 51 11 pm" src="https://user-images.githubusercontent.com/3766511/47625451-9ff3c680-dafb-11e8-93e7-35917905d775.png">
<img width="405" alt="screen shot 2018-10-28 at 9 51 18 pm" src="https://user-images.githubusercontent.com/3766511/47625452-9ff3c680-dafb-11e8-9891-effe79360d71.png">
