### ISSUE TITLE
Task creator has no "create" button

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-web#201]
![screenshot_2018-10-23 create task - taskcluster](https://user-images.githubusercontent.com/28673/47387021-2fecd700-d6dc-11e8-86d3-b6b82b901bbd.png)

It really does, but it's hidden in the hamburger menu way down in the lower-right, along with "reset editor" and "update timestamps".  I think "create" is really the "OK" button for this page, and shouldn't be hidden behind a click/hover[1].  "Reset" is the "cancel" button, and "update timestamps" is sort of a utility function.  I've no idea how best to show the last one.

[1] Actually, it appears to be hover only.  When I go to click on that hamburger it enticingly shows me the options above it, then they disappear.  I just sort of mindlessly did this three times until I stopped and thought about it..

**Comment by helfi92** [comment]
I will try experimenting with having the "OK" button outside the hamburger menu. Nevertheless, we still need to keep the actions close to each other so that we stay consistent across the site.

**Comment by sammysamx20** [comment]
Is this still an issue you want fixed?

**Comment by sammysamx20** [comment]
Would you like the OK button inside as well as outside the hamburger menu?

**Comment by helfi92** [comment]
No need for duplication :)
