### ISSUE TITLE
Remove `onAuthorize` and `onUnauthorize` errors from console

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#204]
Navigate to http://localhost:5080/provisioners. Open devtools to look at the console. There are some warnings in the console. Let's fix the issue.

![screen shot 2018-10-24 at 11 25 14 am](https://user-images.githubusercontent.com/3766511/47442049-9c6ce200-d77f-11e8-98da-c27208bf9cb3.png)

**Comment by codegagan** [comment]
Trying to do setup to see this issue.
