### ISSUE TITLE
Search is sometimes by prefix, sometimes substring

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-web#214]
Sometimes the search box only matches prefixes (e.g., client browser), while sometimes it matches substrings.

Or, a different bug:

The old roles editor matched "roleId containing..", while the new one seems to only search prefixes.

It seems like we should be consistent, but I'd prefer consistently searching substrings (which is sort of what users expect from search)

**Comment by helfi92** [comment]
> Sometimes the search box only matches prefixes (e.g., client browser), while sometimes it matches substrings.

The clients endpoint is paginated and only allows searching via a prefix.

> The old roles editor matched "roleId containing..", while the new one seems to only search prefixes.

The roles view does allow searching by substring but is currently set to "Role starts with" to stay consistent with the clients endpoint since the scopes view uses the same search component for both tabs (roles & clients).

**Comment by djmitche** [comment]
Hm, consistency does sound good.
