### ISSUE TITLE
roles search reloads page, deletes search

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-web#215]
STR:
 * https://taskcluster-web.netlify.com/auth/roles
 * enter "project:releng:ci-group:" in the search
 * hit enter

result: page reloads, showing all (well, one page of) roles

**Comment by djmitche** [comment]
Huh, roles aren't paginated, actually.. is that intentional (since clients are)?

**Comment by helfi92** [comment]
There's an [open bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1455130) to add pagination to roles.

**Comment by djmitche** [comment]
Oh right :)

**Comment by helfi92** [comment]
This has been fixed in https://github.com/taskcluster/taskcluster-web/commit/6207513fd5fb71e57b3b507b80058bff408eaa1d.
