### ISSUE TITLE
Scope explorer hangs browser tab

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-web#217]
Opening the scope explorer on the production instance hangs the tab for a few seconds.

Maybe it should start by displaying nothing, rather than everything, and wait for the user to search?

Or maybe fixing this should wait for the scope UX overhaul, since it's not clear what it should do.

**Comment by helfi92** [comment]
The scope inspector will stop hanging once the roles endpoint becomes paginated. There is already a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1455130) filed for this.

**Comment by djmitche** [comment]
I was surprised that it was hanging the whole tab, rather than just showing a spinner or nothing for a while.  As in, not a slow async operation, but a slow *sync* operation.

**Comment by helfi92** [comment]
This page definitely needs some love. I will try and see what I can do to improve its performance.

**Comment by helfi92** [comment]
@djmitche Do you mind checking if the scope explorer still hangs for you, please?

**Comment by djmitche** [comment]
About 8 seconds of unresponsive UI (clicking does nothing, but curiously the spinner still spins).

But, let's not worry too much about this.  I suspect this tool will change dramatically when we do the scope UX overhaul.

**Comment by helfi92** [comment]
@djmitche Could you try again now, please? It's about 2x faster on my machine now.

**Comment by djmitche** [comment]
Yep, looks a lot better!

**Comment by helfi92** [comment]
Awesome! I will do the same performance work on the other views. Thanks again for filing this issue :)
