### ISSUE TITLE
Show spinner when loading client via search bar

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#221]
Steps to reproduce:

1. Navigate to http://localhost:5080/auth/clients
2. Type something in the search bar (top right of the screen) and press enter

Actual: The table refreshes after a couple of seconds without showing the Spinner component
Expected: The spinner component is displayed  while new data is being fetched

**Comment by sammysamx20** [comment]
@helfi92 I'll take a look at this

**Comment by helfi92** [comment]
@sammysamx20 Awesome! Go for it.

**Comment by sammysamx20** [comment]
@helfi92 Should the root URL for this when I'm setting up the taskcluster-web-server be https://taskcluster.net or should it be another one for this specific project?

**Comment by helfi92** [comment]
In `taskcluster-web-server`, your `user-config.yml` should be:

```yaml
defaults:
  taskcluster:
    rootUrl: https://taskcluster.net
```

**Comment by sammysamx20** [comment]
@helfi92 Yep! Okay Thats what I put thank you! Also, do you know where your spinner component in the source code?

**Comment by helfi92** [comment]
https://github.com/taskcluster/taskcluster-web/search?q=Spinner&unscoped_q=Spinner

```jsx
import Spinner from '@mozilla-frontend-infra/components/Spinner';
```

**Comment by sammysamx20** [comment]
#224 I made a pull request. Please check it out to see if it works!
