### ISSUE TITLE
Signing out not always working

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#226]
STR:

1. Navigate to http://localhost:5080/aws-provisioner/gecko-t-win7-32 while being logged in
2. Sign out

Expected: The user is signed out and the text has been replace with "Sign In"
Actual: The user is not signed out

It appears like when the graphql response returns no result or an error, signing out is not working.

**Comment by alecclarke** [comment]
@helfi92 Could I grab this one?

**Comment by HosseinMarzban** [comment]
Can I work on this issue?

**Comment by helfi92** [comment]
Fixed in https://github.com/taskcluster/taskcluster-web/commit/2c64f3f8b44c1d7113ded5b59503d4f14d0646c3.
