### ISSUE TITLE
Fix landing page when viewing in light theme

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#230]
STR:

1. Navigate to http://localhost:5080/ while being logged out
2. Click the light bulb button in the top app bar

Expected: The page looks decent
Actual: My eyes are bleeding

![screen shot 2018-10-26 at 4 53 41 pm](https://user-images.githubusercontent.com/3766511/47592110-eef4fc80-d93f-11e8-862b-6b5cada49913.png)

To fix this problem, refer to https://github.com/taskcluster/taskcluster-web/blob/master/src/theme.js.

**Comment by sumitjoshi97** [comment]
I would like to look in this. Any ideas for changes?

**Comment by helfi92** [comment]
Fixed in https://github.com/taskcluster/taskcluster-web/commit/79820758f873fa9e55e1dce49d2e88bc97b36c51.
