### ISSUE TITLE
Fix logviewer in light theme

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#247]
1. The logviewer in light theme should look exactly like the dark theme one
2. The fab buttons (top right) should have icons be white (right now they're black)

### Dark Theme

![screen shot 2018-10-30 at 4 59 41 pm](https://user-images.githubusercontent.com/3766511/47750189-3a234e00-dc65-11e8-8940-67341f387b37.png)

### Light Theme

![screen shot 2018-10-30 at 4 56 48 pm](https://user-images.githubusercontent.com/3766511/47750061-df89f200-dc64-11e8-8a93-a2bf2440d760.png)

Here's a link to access the logviewer: http://localhost:5080/tasks/A4DXEeUdQkmSP7xfALz6iA/runs/0/logs/https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FA4DXEeUdQkmSP7xfALz6iA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

**Comment by robbykim** [comment]
I'll take a stab at this issue!

**Comment by helfi92** [comment]
Go for it! Let me know if you have any questions.

**Comment by robbykim** [comment]
I'm having some trouble getting the web server going. `yarn` is running into some issues with a package not found in the npm registry. Is this anything known?

**Comment by osanche1** [comment]
I tried to take a look at the link but it was down. Has the issue been resolved? I noticed Robby fixed a couple of icons but not the rest.

**Comment by helfi92** [comment]
@osanche1 Feel free to tackle the actual log background issue. The icons are being taken care in  https://github.com/taskcluster/taskcluster-web/pull/251.

For the logviewer, I think we just need to make sure it looks exactly like the dark theme one.
