### ISSUE TITLE
Artifact links all try to display in log viewer

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-web#253]
https://taskcluster-web.netlify.com/tasks/A73VbaXFRSCm5LRvKfB4Iw/runs/0/logs/https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FA73VbaXFRSCm5LRvKfB4Iw%2Fruns%2F0%2Fartifacts%2Fpublic%2Fbuild%2Fsetup.exe

For the most part, I think we should be linking to artifacts in a new browser tab and letting the browser figure out how to display them.  Basically, what tools has been doing all along.

The tools task inspector did a smart thing and privileged `public/logs/live.log` as the "main" log for the run.  It would be great to be able to get to that with one click, without opening artifacts and looking for it (in what may be a long list).

It might be good to do some filename filtering, and if an artifact ends in ".log", perhaps making it link by default to the log viewer.

**Comment by helfi92** [comment]
@djmitche Has your issue been resolved?

**Comment by djmitche** [comment]
I think so!
