### ISSUE TITLE
Can't select workerId

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-web#255]
STR:

*  https://taskcluster-web.netlify.com/tasks/ZxDcIF_MR7uh__aDdgxCGQ/runs/0
* Click to one side of the workerId and drag to select (with or without holding a modifier key)

Expected: text selection

Actual: panel activates for drag-and-drop

**Comment by helfi92** [comment]
@djmitche https://deploy-preview-260--taskcluster-web.netlify.com/tasks/ZxDcIF_MR7uh__aDdgxCGQ/runs/0.

**Comment by djmitche** [comment]
:heart: looks great!
