### ISSUE TITLE
Visual indication of a task group state

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#270]
A user will want to do other things while waiting for a task group to finish. This can be solved by modifying the favicon to have a yellow, green or red circle beside the Logo to indicate the status of a task group. When the user leaves the task group view, we should bring back the original favicon.

**Comment by helfi92** [comment]
Instead of creating 3 other icons, we should create a component that renders an svg and takes a  `status` prop. We could default to the original logo when the `status` is not provided.

**Comment by projectyang** [comment]
@helfi92 , I'd like to take this on. :)

**Comment by helfi92** [comment]
@projectyang Awesome! Do you have something like Sketch or Photoshop to design the svg? If not, that's okay. I can create the icon for you and you could hook it up. Let me know what works best for you.

**Comment by projectyang** [comment]
@helfi92, I'm happy to do it as well.

**Comment by helfi92** [comment]
Thank you! Ok here's some more info:

1. Use https://github.com/taskcluster/taskcluster-web/blob/master/logo.png for the logo
2. Use a design tool (sketch/photoshop) to create an svg which includes the logo and a status circle similar to https://github.com/taskcluster/taskcluster-tools/blob/master/src/images/taskcluster-group-failed.png except that the Logo will be a React component.
3. Modify https://github.com/taskcluster/taskcluster-web/blob/master/src/views/Tasks/TaskGroup/index.jsx to show the Logo with the appropriate circle colors
4. Once the user navigates away from the group view, we should bring back the original logo. I think this logic could probably be added in `componentWillUnmount`.

**Comment by projectyang** [comment]
@helfi92

I can't seem to figure out how to create taskgroup and be able to view it locally. I try to create a task and receive 'ext.certificate must be a JSON object' as an error message. Any tips?

**Comment by helfi92** [comment]
Try logging out and logging back in. Make sure you don't put anything in the JSON certificate field.

![screen shot 2018-11-07 at 6 17 20 pm](https://user-images.githubusercontent.com/3766511/48167349-6c622a80-e2b9-11e8-958b-12f4187c6e53.png)

**Comment by helfi92** [comment]
You can get the access token from the [Taskcluster CLI](https://github.com/taskcluster/taskcluster-web-server#taskcluster-credentials).

**Comment by projectyang** [comment]
Thanks! Works now. 

To clarify again, you want the favicon to dynamically display the task group status via coloured circles in the Task Group view?

![screen shot 2018-11-08 at 5 33 51 pm](https://user-images.githubusercontent.com/13473834/48231580-a5af9e80-e37c-11e8-9106-f19ba291404d.png)

**Comment by helfi92** [comment]
Yep :)

**Comment by helfi92** [comment]
How is it going @projectyang? Let me know if you have questions.

**Comment by projectyang** [comment]
@helfi92 

Making progress! I do have a few questions:

1. Currently, I've only managed to manipulate the favicon link via using document.head. E.g. removing and appending new link tags. Can you provide an example of using a react component instead?

2. To confirm the logic for the favicon states:

Green will only display if all tasks have been run and are completed.
Yellow will display for when there are tasks currently pending/scheduled/unscheduled/running.
Red will only display if all tasks have been run and there are ones that have failed/exception.

3. Is the best approach to derive favicon state through Props->taskGroup->edges?

**Comment by helfi92** [comment]
> Currently, I've only managed to manipulate the favicon link via using document.head. E.g. removing and appending new link tags. Can you provide an example of using a react component instead?

Hm, I'm afraid we won't be able to use a react component to modify the favicon. We coud however use [`react-helmet`](https://github.com/nfl/react-helmet) to manipulate the favicon.

> Green will only display if all tasks have been run and are completed.
Yellow will display for when there are tasks currently pending/scheduled/unscheduled/running.
Red will only display if all tasks have been run and there are ones that have failed/exception.

Yes, yes, no. Red will display whenever there is at least 1 failed task.

> Is the best approach to derive favicon state through Props->taskGroup->edges?

Hm, we might be able to use `statusCount` to inspect the count. https://github.com/taskcluster/taskcluster-web/blob/master/src/components/TaskGroupProgress/index.jsx#L183.

**Comment by helfi92** [comment]
Since we won't be able to manipulate the favicon using React, we can lean toward multiple icon files, similar to how it's done in https://github.com/taskcluster/taskcluster-tools/tree/master/src/images.

**Comment by helfi92** [comment]
@projectyang It seems to work locally but doesn't seem to load properly in production: https://taskcluster-web.netlify.com/tasks/groups.

**Comment by projectyang** [comment]
@helfi92 

I think this has do with webpack and how it imports local images. Can we try if this works to fix? Should I create a new issue/branch for this?

```
      <ReactHelmet>
        {state ? (
          <link
            // eslint-disable-next-line global-require,import/no-dynamic-require
            href={require(`../../images/logo${state[0] +
              lowerCase(state).slice(1)}.png`)}
            rel="shortcut icon"
          />
        ) : (
          // eslint-disable-next-line global-require
          <link href={require('../../images/logo.png')} rel="shortcut icon" />
        )}
        {title && <title>{title}</title>}
      </ReactHelmet>
```

**Comment by helfi92** [comment]
You're right. Given that we only have 4 small images, we can just import them at the top of the file.

```jsx
import Logo from ...
import LogoFailed from ...
import LogoCompleted from ...
import LogoRunning from ...

...

render() {
 ...
 <link href={<Logo... />}
}
```

I think we do something similar in taskcluster/taskcluster-tools.
