### ISSUE TITLE
Mobile issue (logo)

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#285]
STR:

1. Navigate to localhost:5080
2. Resize the screen until the navigation bar collapses
3. Click the hamburger icon (the three horizontal lines)
4. Hover on the text "Taskcluster"

Expected: The "T" logo should be relatively same size as the hamburger menu
Actual: The "T" logo is much bigger than the hamburger menu

<img width="588" alt="screen shot 2018-11-14 at 11 51 12 am" src="https://user-images.githubusercontent.com/3766511/48498344-1125c000-e804-11e8-9053-2503abd5f71b.png">

**Comment by OjaswinM** [comment]
Hi, this is my first time contributing. Can I give this a try?

**Comment by helfi92** [comment]
Go for it :)
