### ISSUE TITLE
Landing page scrolling issue

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#294]
Steps to reproduce:

1. Navigate to https://taskcluster-web.netlify.com/ or localhost:5080/ while being logged out
2. Scroll the main content horizontally

Expected: The content doesn't scroll
Actual: The content scrolls in the horizontally

**Comment by OjaswinM** [comment]
Hey, I would like to try this. Any idea what could be causing this?

**Comment by OjaswinM** [comment]
Alright, I'm on it

**Comment by eduardoltorres** [comment]
Hey, how's it going?

I'm available if you need any help!
(got redirected here from codetribute.mozilla.org)

**Comment by helfi92** [comment]
Hey @eduardoltorres, feel free to tackle this issue.

**Comment by eduardoltorres** [comment]
@helfi92 cool! I'm on it. Thanks!

Will come back with questions if any (first issue here).

**Comment by OjaswinM** [comment]
Hey @eduardoltorres, sorry I got busy with my college submissions. I fixed the horizontal scroll on the Landing component by changing width from 100vw to 100% in the Landings component.

https://github.com/taskcluster/taskcluster-web/blob/80aef38b10173ce2b7e80aba0113272e90262ad8/src/components/Landing/index.jsx#L10-L18
However, this doesn't fix the horizontal scroll on the whole page so you can try looking into it :)

**Comment by eduardoltorres** [comment]
@OjaswinM alright, cool! I'll leave you to it then. If you need any help, just let me know 😀

**Comment by OjaswinM** [comment]
Haha alright, I'll create a PR. Sorry for being late on this.
