### ISSUE TITLE
Allow users to be notified when the interactive status is ready

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#304]
STR:

1. Navigate to https://taskcluster-web.netlify.com/tasks/create/interactive and make sure you are logged in
2. Click on "+". You will be redirected to the connect page.

![screen shot 2018-12-11 at 2 54 36 pm](https://user-images.githubusercontent.com/3766511/49826337-b628af80-fd54-11e8-94d1-77519f68d4dc.png)

Expected: The connect page gives the user the option to be notified when the interactive status is ready
Actual: There is nothing in place to notify the user when the interactive status is ready

**Comment by helfi92** [comment]
We could have a [fab button](https://material-ui.com/demos/buttons/#floating-action-buttons) in the bottom right with the bell icon from [mdi-react](https://materialdesignicons.com/). To actually hook-up the notification logic, we can use the [Notification](https://developer.mozilla.org/en-US/docs/Web/API/notification) API.

**Comment by helfi92** [comment]
Clicking on the bell icon would turn on/off notification. We could use the following icons from mdi-react:

```jsx
import BellIcon from 'mdi-react/BellIcon';
import BellOffIcon from 'mdi-react/BellOffIcon';
```

**Comment by rahulrj25** [comment]
I am a beginner and would like to work on this issue.

**Comment by helfi92** [comment]
Go for it :)

**Comment by rahulrj25** [comment]
@helfi92 Can you help me understand the codebase or which file needs to be modified and how to log-in TaskCluster ?

**Comment by helfi92** [comment]
The instructions to logging in to taskcluster are outlined in the [README](https://github.com/taskcluster/taskcluster-web#web-server). Let me know if there is anything unclear. Also, this issue relates to the task interactive view. The code for this view can be found [here](https://github.com/taskcluster/taskcluster-web/blob/master/src/views/Tasks/InteractiveConnect/index.jsx). Hope that helps.

**Comment by rahulrj25** [comment]
Thanks @helfi92 . I am having trouble launching TC web on local machine. I have created .env file, can you specify next steps ?

**Comment by rahulrj25** [comment]
Is it necessary to setup server ? I haven't till now. And I have to run index.jsx to launch TC ?

**Comment by helfi92** [comment]
Yes it is necessary to have the server.

To launch taskcluster-web, from your terminal you run ‘yarn install’ to install the dependencies then ‘yarn start’.

**Comment by rahulrj25** [comment]
I am getting following error :
./src/components/Shell/index.jsx
Module not found: Error: Can't resolve 'docker-exec-websocket-server' in 'C:\Users\Rahul\Downloads\taskcluster-web\src\components\Shell'

Also while setting up server there is no file named user-config.yml, I have copied content of user-config.yml in config.yml. Let me know if this is correct.

**Comment by helfi92** [comment]
> I am getting following error :
./src/components/Shell/index.jsx
Module not found: Error: Can't resolve 'docker-exec-websocket-server' in 'C:\Users\Rahul\Downloads\taskcluster-web\src\components\Shell'

Ah, that's probably because of your python version. Give the following a shot: https://github.com/taskcluster/taskcluster-web/issues/306#issuecomment-446611865

> Also while setting up server there is no file named user-config.yml, I have copied content of user-config.yml in config.yml. Let me know if this is correct.

From the [README in taskcluster-web-server](https://github.com/taskcluster/taskcluster-web-server#running-taskcluster-web-server-locally):

The taskcluster.rootUrl configuration setting is required. Either set TASKCLUSTER_ROOT_URL in your environment, or copy `user-config-template.yml` to `user-config.yml` and edit it to include the rootUrl for the Taskcluster instance you are accessing; for example https://taskcluster.net.

Hope that helps.

**Comment by rahulrj25** [comment]
I did a typo, I copied content of user-config-template.yml to config.yml, there no file named user-config.yml.

**Comment by helfi92** [comment]
> I did a typo, I copied content of user-config-template.yml to config.yml, there no file named user-config.yml. I have followed rest of instructions.

Right, there is no file named `user-config.yml` because you have to create it.

1. Create `user-config.yml`
2. Copy the content of `user-config-template.yml` into `user-config.yml`
3. Edit `user-config.yml` to have the rootUrl set to `https://taskcluster.net` instead of `...`

**Comment by rahulrj25** [comment]
Yes finally it is running and I have signed-in. In the interactive connect page when does Interactive status change ? How do we want the notification to be sent ?

**Comment by helfi92** [comment]
> Yes finally it is running and I have signed-in

Great to hear!

I just realized this is a duplicate of another issue that is being worked on by someone else... Hmm, do you mind if we try to find you another issue to work on? I want to make sure there is no overlap work. Do you want to work on https://github.com/taskcluster/taskcluster-web/issues/354 instead? I would be happy to mentor. Comment on the issue directly if you're interested.

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/e3516eae173232065cb73d69636123feba08fcd1.
