### ISSUE TITLE
Can't copy link from artifacts links

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-web#306]
![screenshot](https://user-images.githubusercontent.com/28673/49831828-ebd49500-fd62-11e8-9b39-3e15fd65b287.png)

I'd like to copy the link to the file so that I can paste it, without first downloading it, but there's no "copy link location" in the context menu.

Related to #253.

**Comment by djmitche** [comment]
(same occurs if I right-click the link icon on the right of the row)

**Comment by helfi92** [comment]
Fair enough. We should add a copy icon similar to how it's done on some other list items:

<img width="685" alt="screen shot 2018-12-11 at 8 34 03 pm" src="https://user-images.githubusercontent.com/3766511/49841102-403c3c80-fd84-11e8-97fa-19cc9bec0539.png">

**Comment by helfi92** [comment]
STR:

1. Navigate to https://taskcluster-web.netlify.com/tasks/b4UAjb67QiGP0DMjh3Qpaw or `localhost:5080/tasks/b4UAjb67QiGP0DMjh3Qpaw`
2. Click the Artifacts dropdown list item

<img width="768" alt="screen shot 2018-12-11 at 8 36 51 pm" src="https://user-images.githubusercontent.com/3766511/49841205-b50f7680-fd84-11e8-97fd-7ac075bfff6e.png">


Expected: There is a copy icon allowing a user to copy the artifact name

Actual: There is no easy way to copy the artifact name without having the link be clicked

**Comment by nvamsikrishna05** [comment]
I would like to work on this issue

**Comment by helfi92** [comment]
Awesome, go for it :) Let me know if you had questions.

**Comment by nvamsikrishna05** [comment]
After I cloned and ran npm install I am getting the following error.
![error](https://user-images.githubusercontent.com/12725742/49872899-7ccd6e00-fe40-11e8-813d-103942655c62.PNG)

Need help on this.

**Comment by helfi92** [comment]
You'll want to use `yarn` instead of `npm` to install the dependencies. When you run `yarn install`, it will look at `yarn.lock` to figure out the exact versions of the dependencies to install. `npm` uses `package-lock.json` (we don't use that in this project). I would do something like:

```bash
rm package-lock.json
rm -rf node_modules/
yarn install
yarn start
```

Let me kow how that goes.

**Comment by nvamsikrishna05** [comment]
> You'll want to use `yarn` instead of `npm` to install the dependencies. When you run `yarn install`, it will look at `yarn.lock` to figure out the exact versions of the dependencies to install. `npm` uses `package-lock.json` (we don't use that in this project). I would do something like:
> 
> ```shell
> rm package-lock.json
> rm -rf node_modules/
> yarn install
> yarn start
> ```
> 
> Let me know how that goes.

![error3](https://user-images.githubusercontent.com/12725742/49874338-41cd3980-fe44-11e8-9df8-cbcdfd2ef8bc.PNG)
Still I have some errors after running `yarn install`

**Comment by helfi92** [comment]
Which version of node are you using?

```bash
node -v
```

**Comment by djmitche** [comment]
It looks like you only have Python 3 installed. Why the buffertools build
process requires Python, I couldn't tell you.  But try installing Python
2.7?

**Comment by nvamsikrishna05** [comment]
> Which version of node are you using?
> 
> ```shell
> node -v
> ```

node version - 10.13

**Comment by nvamsikrishna05** [comment]
> It looks like you only have Python 3 installed. Why the buffertools build process requires Python, I couldn't tell you. But try installing Python 2.7?

yes, I have only python 3 installed. I'll try python 2

**Comment by nvamsikrishna05** [comment]
I have install python2 also and tried. Again I am getting error but the error changed compared to previous attempts.
![error](https://user-images.githubusercontent.com/12725742/49882003-a80e8800-fe55-11e8-9b4d-d70908359050.PNG)

**Comment by nvamsikrishna05** [comment]
Plus When I run `yarn run start`. I get the following errors too many of them and When I search those, they seem to be for windows if the project was mainly done in unix due to how windows and unix handle linebreaks and stuff. So, How I suppress/fix those without affecting others ?

and yes, that error while installing packages is still there to resolve.
![error2](https://user-images.githubusercontent.com/12725742/49882317-5f0b0380-fe56-11e8-9fd6-c36c2b3fe96e.PNG)

**Comment by helfi92** [comment]
> How I suppress/fix those without affecting others ?

You can try adding

```js
'linebreak-style': 'off',
```

after line 21 https://github.com/taskcluster/taskcluster-web/blob/590acb2fb15d5feb849903e33ee643eb5fd09ac0/.neutrinorc.js#L21

**Comment by helfi92** [comment]
> I have installed python2 and tried. Again I am getting error but the error changed compared to previous attempts.

Did you try removing `node_modules/` and starting again?

```jsx
rm -rf node_modules/
yarn install
```

**Comment by nvamsikrishna05** [comment]
> > I have installed python2 and tried. Again I am getting error but the error changed compared to previous attempts.
> 
> Did you try removing `node_modules/` and starting again?
> 
> ```js-jsx
> rm -rf node_modules/
> yarn install
> ```

yes, Did that.

**Comment by helfi92** [comment]
What happens when you do `yarn start`. Are you able to run the application on `localhost:5080`?

**Comment by nvamsikrishna05** [comment]
> What happens when you do `yarn start`. Are you able to run the application on `localhost:5080`?

Now, I can start the application after adding that linebreakstyle fix.

Now when I navigate to the Issue reproducing URL : 
`http://localhost:5080/tasks/b4UAjb67QiGP0DMjh3Qpaw`
I get the following error.
Network error: Unexpected token E in JSON at position 0

**Comment by helfi92** [comment]
I suspect the web server is not running. https://github.com/taskcluster/taskcluster-web#web-server. Let me know if that fixes it.

**Comment by nvamsikrishna05** [comment]
> I suspect the web server is not running. https://github.com/taskcluster/taskcluster-web#web-server. Let me know if that fixes it.

Well, I cloned it and ran it. But I am now confused. So I need to run first this web-server on port 5080 and then run current UI project on which port ?

When I ran web-server on port 5080 and then try to run UI  it doesnt run.
![error3](https://user-images.githubusercontent.com/12725742/49885712-f32c9900-fe5d-11e8-8ec4-c241f77a2b19.PNG)

**Comment by helfi92** [comment]
> When I ran web-server on port 5080 and then try to run UI it doesnt run.

For development, `taskcluster-web-server` process must be serving on http://localhost:3050. This is actually already specified in `config.yml` so you don't need to change that value. All you have to do in tc-web-server is include the rootUrl. https://github.com/taskcluster/taskcluster-web-server#running-taskcluster-web-server-locally.

**Comment by helfi92** [comment]
To recap:

- `tc-web` is already configured to run on port 5080. See [here](https://github.com/taskcluster/taskcluster-web/blob/590acb2fb15d5feb849903e33ee643eb5fd09ac0/.neutrinorc.js#L48). Leave as is.
- `tc-web-server` runs on port 3050. See [here](https://github.com/taskcluster/taskcluster-web-server/blob/d080307ea49b591996e69d95305670a01588b4e6/config.yml#L45). Leave as is.
- In `tc-web-server`, copy `user-config-template.yml` to `user-config.yml` and edit it to include the rootUrl for the Taskcluster instance you are accessing; for example `https://taskcluster.net`.

Start the server with `yarn start` then start the client with `yarn start`.
