### ISSUE TITLE
Monitor performance regressions from tools.taskcluster.net

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster-web#309]
As a release engineer, I frequently lean on Taskcluster tooling to quickly help me diagnose build issues - most frequently, I just need to see the logs for a build.

As we migrate to `taskcluster-web`, I'll be super appreciative if we can ensure that we don't significantly increase load times.
For example, when investigating the new build configuration of `reference-browser`, I may view a task group. When comparing between `taskcluster-web` and the old taskcluster tools site, I find that:
* Old taskcluster consistently takes < 5 seconds to load. [example link](https://tools.taskcluster.net/groups/XO7YOMp_R0SoOw0UJ_cIZw)
* `taskcluster-web` seems to be taking ~ 30 seconds to load [example link, same task group ID](https://taskcluster-web.netlify.com/tasks/groups/XO7YOMp_R0SoOw0UJ_cIZw)

[old-taskcluster.har.txt](https://github.com/taskcluster/taskcluster-web/files/2673931/old-taskcluster.har.txt)
[new-taskcluster-web.har.txt](https://github.com/taskcluster/taskcluster-web/files/2673933/new-taskcluster-web.har.txt)

When just needing to quickly view a log, having to wait 30 seconds may impact my productivity/train of thought.
Otherwise, I'm really enjoying the usability of the new Taskcluster though, looks great! Thanks for the good tooling :smile:

**Comment by helfi92** [comment]
Thank you for reaching out. I can definitely replicate. It's interesting that this only happens in production but seems to be fast when running locally. I'll look into it.

**Comment by helfi92** [comment]
<img width="860" alt="screen shot 2018-12-12 at 11 15 18 pm" src="https://user-images.githubusercontent.com/3766511/49915478-dbf0aa00-fe63-11e8-8d29-482777f920a4.png">

The slowness seems to come from fetching the task actions (~30 seconds). This is weird. I'll continue looking into it tomorrow :)

**Comment by mitchhentges** [comment]
:+1: nice, much better! It's taking ~3s to load the new taskcluster UI now :)
I'll leave this ticket here:
* If you'd like to close it, that's :+1:
* Alternatively, it might still be a valid feature request to have monitoring/comparison of loading times between new and old taskcluster.

Up to you guys :smile:
