### ISSUE TITLE
Show the `NotFound` page when there is no route match

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#317]
Investigate why the `NotFound` view is not being displayed when a user navigates to a route that doesn't exist (e.g., https://taskcluster-web.netlify.com/123456789).

https://github.com/taskcluster/taskcluster-web/blob/590acb2fb15d5feb849903e33ee643eb5fd09ac0/src/App/routes.jsx#L101-L105

**Comment by baronKilljoy** [comment]
I would like to work in this. I think its just missing the path.

**Comment by helfi92** [comment]
Go for it :)

**Comment by baronKilljoy** [comment]
Is there any documentation on the path variable here. I am wondering why you use path: '/aws-provisioner' in stead of path: '/AwsProvisioner'

**Comment by helfi92** [comment]
The NotFound page should render whenever a path doesn't match with anything else similar to how it's done in https://reacttraining.com/react-router/web/example/no-match. In other words, the NotFound Page should show whenever a user types something like:

```
localhost:5080/foo
localhost:5080/bar
localhost:5080/baz
localhost:5080/12345
localhost:5080/98765
localhost:5080/alsdlkasdjlkasjlkdasjkl
```

**Comment by baronKilljoy** [comment]
It looks like there are some places the code redirects 404s to index.html.  In the dev server folder
index.js
`module.exports = (neutrino, options = {}) => {
  neutrino.config.devServer.merge({
    port: 5000,
    hot: true,
    // Redirect 404s to index.html, so that apps that use the HTML 5 History API work.
    historyApiFallback: true,
    // Only display compile duration and errors/warnings, to reduce noise when rebuilding.
    stats: {
      all: false,
      errors: true,
      timings: true,
      warnings: true
    },
    ...options
  });
};
`
and require.js has a comment saying there isn't an event listener because of a IE bug
`                //It would be great to add an error handler here to catch
                //404s in IE9+. However, onreadystatechange will fire before
                //the error handler, so that does not help. If addEventListener
                //is used, then IE will fire error before load, but we cannot
                //use that pathway given the connect.microsoft.com issue
                //mentioned above about not doing the 'script execute,
                //then fire the script load event listener before execute
                //next script' that other browsers do.
                //Best hope: IE10 fixes the issues,
                //and then destroys all installs of IE 6-9.
                //node.attachEvent('onerror', context.onScriptError);`

**Comment by helfi92** [comment]
> It looks like there are some places the code redirects 404s to index.html. In the dev server folder
index.js
module.exports = (neutrino, options = {}) => { neutrino.config.devServer.merge({ port: 5000, hot: true, // Redirect 404s to index.html, so that apps that use the HTML 5 History API work. historyApiFallback: true, // Only display compile duration and errors/warnings, to reduce noise when rebuilding. stats: { all: false, errors: true, timings: true, warnings: true }, ...options }); }; 

This is expected since we are dealing with a single page application. Whenever a user tries to navigate to a certain path in the URL, the site will **always** send the user to `index.html` first. `index.html` will then use `react-router` to determine which route/component to render.

What I think is happening is that a path like `localhost:5080/alsdlkasdjlkasjlkdasjkl` is being matched to

```jsx
{
  component: lazy(() =>
    import(/* webpackChunkName: 'HomeOrDashboard' */ '../views/HomeOrDashboard')
  ),
  path: '/',
},
```

What we probably want to do is add `exact: true` so that it fallsback to the `NotFound` view.

```jsx
{
  component: lazy(() =>
    import(/* webpackChunkName: 'HomeOrDashboard' */ '../views/HomeOrDashboard')
  ),
  path: '/',
  exact: true,
},
```

Give that a shot and let me know how that goes. Feel free to open a pull-request if it works :)

**Comment by baronKilljoy** [comment]
Your fix worked, but cant commit because of a line style error
![errormess](https://user-images.githubusercontent.com/36493475/50245301-1dbbac00-03a0-11e9-86f0-8f4fbc939617.jpg)

**Comment by helfi92** [comment]
Ah, I believe this is a issue only on windows. Try adding [the following](https://github.com/taskcluster/taskcluster-web/issues/306#issuecomment-446646349) in `.neutrinorc.js` and committing it as well.

**Comment by baronKilljoy** [comment]
pull request made, thanks for your help. Hope to work with you again.

**Comment by helfi92** [comment]
My pleasure!

**Comment by Shivansh2407** [comment]
Is the issue still pending?

**Comment by helfi92** [comment]
Oops, I forgot to close this issue. It was fixed.
