### ISSUE TITLE
[ErrorPanel] Fix background color for <code>

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#324]
STR: https://taskcluster-web.netlify.com/tasks/groups/WMUwxFWUSfq7QV4uESr7JQ

This happens when an `ErrorPanel` uses the `<code>` element.

<img width="1394" alt="screen shot 2018-12-20 at 1 53 35 pm" src="https://user-images.githubusercontent.com/3766511/50304715-b57fcf80-045e-11e9-9559-8595ce26f13b.png">

**Comment by arshadkazmi42** [comment]
I would like to take this up.
Which color are planning to add in `<code>`

**Comment by helfi92** [comment]
Go for it :)

> Which color are planning to add in `<code>`

I'm not sure yet. You can also try looking at https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/styles/colorManipulator.js to see if there's anything interesting we might use from there (e.g, the `lighten` or `fade` functions). You can have access to those functions via:

```jsx
import { <function-that-you-want-to-use> } from '@material-ui/core/styles/colorManipulator;
```

I've used that a [couple of times](https://github.com/taskcluster/taskcluster-web/search?q=colorManipulator&unscoped_q=colorManipulator) in this repo. By the way, the [ErrorPanel](https://mozilla-frontend-infra.github.io/components/#errorpanel) background becomes yellowish when the `warning` prop is set (i.e., `<ErrorPanel warning  ... />`.

**Comment by arshadkazmi42** [comment]
I started looking into this, did reproduce this issue in my local environment.
I reached to this component
https://github.com/taskcluster/taskcluster-web/blob/master/src/components/ErrorPanel/index.jsx
But I don't see this component is handling the <code>code</code> part.
Where exactly I need to be looking for this code.

**Comment by helfi92** [comment]
You can try looking at https://github.com/taskcluster/taskcluster-web/blob/master/src/App/Main.jsx. Does that help?

**Comment by arshadkazmi42** [comment]
I tried editing this part of code, but it does not changes anything 

https://github.com/taskcluster/taskcluster-web/blob/master/src/App/Main.jsx#L40-L42

Is this the css for `<code>`?

**Comment by helfi92** [comment]
Try doing the following and see if it works:

1. Add the following in the mixins section of `theme.js`:

```diff
diff --git a/src/theme.js b/src/theme.js
@@ -88,6 +88,11 @@ const createTheme = isDarkTheme => ({
   drawerWidth: THEME.DRAWER_WIDTH,
   docsDrawerWidth: THEME.DRAWER_WIDTH + 125,
   mixins: {
+    errorPanel: {
+      '& code': {
+        color: lighten('#fff', 0.2),
+      },
+    },
```

2. For every `ErrorPanel` that includes the `warning` prop, include the class from step 1:

```jsx
errorPanel: {
  ...theme.mixins.errorPanel,
},
```

```jsx
<ErrorPanel warning className={classes.errorPanel} ... />
```

Let me know how that goes.

**Comment by arshadkazmi42** [comment]
I did above change, this is how it looks.

![screenshot from 2018-12-25 13-09-16](https://user-images.githubusercontent.com/4654382/50416568-60b9cb80-0847-11e9-95b2-610947ff1e42.png)

If this is fine, I can update it everywhere and create a PR.
Or should we change the background color also?

**Comment by helfi92** [comment]
> I did above change, this is how it looks.

The text inside the <code> element looks good.

> If this is fine, I can update it everywhere and create a PR.

Note that we use the ErrorPanel in every view however we use the warning prop only in a handful of places. Please don’t change every ErrorPanel. Only change those that have the warning prop on them.

> Or should we change the background color also?

I’m not sure there is something bad about the background colour. Let’s keep it the way it is.

**Comment by arshadkazmi42** [comment]
> Note that we use the ErrorPanel in every view however we use the warning prop only in a handful of places. Please don’t change every ErrorPanel. Only change those that have the warning prop on them.

Cool. I will create a PR in sometime. :+1:
