### ISSUE TITLE
Remove duplicate navigation bars

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#331]
STR:

1. Navigate to http://localhost:5080/shell

<img width="1680" alt="screen shot 2018-12-24 at 3 48 50 pm" src="https://user-images.githubusercontent.com/3766511/50406467-8eddd380-0793-11e9-848c-a9db411e7013.png">

Actual: There are 2 navigation bars on the left

Expected: There is 1 navigation bar on the left

**Comment by arshadkazmi42** [comment]
I can take this up.

**Comment by helfi92** [comment]
Go for it.

**Comment by arshadkazmi42** [comment]
I started looking into this.
look's like its failing only in firefox. Its working fine in chrome.

Any tips, where should I look for this issue? I tried debugging in `Shell` component and view.

**Comment by helfi92** [comment]
Indeed, this is really strange. I think the problem is in this file https://github.com/taskcluster/taskcluster-web/blob/master/src/components/Shell/index.jsx

**Comment by arshadkazmi42** [comment]
Looks like its due to this
`ref={this.registerChild} ` I am still trying to find the exact issue.

**Comment by helfi92** [comment]
> Looks like its due to this `ref={this.registerChild}`

I agree.

**Comment by helfi92** [comment]
I looked into it and believe there is a bug in the `hterm` library. I created https://github.com/dbkaplun/hterm-umdjs/issues/6.

**Comment by arshadkazmi42** [comment]
@helfi92 Ok. I think once that is merged, it will fix this issue also.

**Comment by helfi92** [comment]
Continued in https://github.com/taskcluster/taskcluster/issues/217.
