### ISSUE TITLE
Notify user when an interactive task is ready

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#332]
STR:

1. Navigate to http://localhost:5080/tasks/create/interactive. Make sure you are logged in.
2. Click the "+" icon to create a task
3. You will be navigated to a screen with the "Interactive Status" state set to "Waiting"

<img width="1680" alt="screen shot 2018-12-24 at 4 07 11 pm" src="https://user-images.githubusercontent.com/3766511/50406827-cd768c80-0799-11e9-8b10-62c57a88558f.png">

4. Wait until the session is ready. The waiting time may vary. You will know that a session is ready when you are given the option to select a session.

<img width="1678" alt="screen shot 2018-12-24 at 4 33 54 pm" src="https://user-images.githubusercontent.com/3766511/50406825-c8194200-0799-11e9-9053-5f6d185921b9.png">

**Task**: Notify the user via the [Notifications API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API) when the session is ready.

#### Tips

* The code that figures out when a session is ready can be found here:

https://github.com/taskcluster/taskcluster-web/blob/9bcadb1cac7eb8c8227579a2fb343aae8e8c689f/src/views/Tasks/InteractiveConnect/index.jsx#L256-L257

* Waiting for a session to be ready can sometimes take a long time. Feel free to temporarily set `isSessionReady` to true or having it become truthy after a small delay (via usage of window.setTimeout).

**Comment by oksmelnik** [comment]
I'd like to work on this issue

**Comment by helfi92** [comment]
Go for it.

**Comment by oksmelnik** [comment]
well, yes - I have one question. How do I log in? I followed the instructions at Auth0 Config section here https://github.com/taskcluster/taskcluster-web 
but asked to sign in anyway

**Comment by helfi92** [comment]
Ah, to login, all you have to do is:

1. Acquire Taskcluster credentials via `taskcluster-cli`. This is explained in the server repo taskcluster-web-server. See [here](https://github.com/taskcluster/taskcluster-web-server#taskcluster-credentials) for instructions. Basically you'll have to go to the [installation section](https://github.com/taskcluster/taskcluster-cli#installation) of [taskcluster-cli](https://github.com/taskcluster/taskcluster-cli) and download the taskcluster binary. Once downloaded, all you have to do is run `eval $(./taskcluster signin --name taskcluster-web-server)` in the directory where that binary is installed. This will open a browser for you to login. Once you successfuly login, the credentials will be outputted in the terminal. You use those manual credentials to login in taskcluster-web.

2. Have `taskcluster-web-server` running in a second terminal. You can do that by cloning the repo, then running `yarn install` to install the dependencies then `yarn start` to start the server. Don't forget to set the rootUrl to `https://taskcluster.net` as instructed [here](https://github.com/taskcluster/taskcluster-web-server#running-taskcluster-web-server-locally).

Hope that helps. Let me know if there is anything else that is confusing.

**Comment by oksmelnik** [comment]
Thank you, was able to login! Will continue on the issue this week

**Comment by helfi92** [comment]
Hey @oksmelnik, how is it going? Do you have any questions for me? :)

**Comment by ededals** [comment]
Hey @helfi92 will work on this issue.

**Comment by helfi92** [comment]
Go for it.

**Comment by ededals** [comment]
Hi, It seems that I have to log in to be able to create new task and the system is requesting credentials. What are the credentials to sign in?

**Comment by helfi92** [comment]
https://github.com/taskcluster/taskcluster-web/issues/332#issuecomment-451145035

**Comment by ededals** [comment]
Once I run `taskcluster signin --name taskcluster-web-server ` a browser window is open at url `https://tools.taskcluster.net/auth/clients/` requesting to sign in. How can I sign in there?

**Comment by helfi92** [comment]
Use the drop-down located top right and click on "Sign in with Auth0"

<img width="313" alt="screen shot 2019-01-24 at 11 31 55 pm" src="https://user-images.githubusercontent.com/3766511/51725451-43d40c00-2030-11e9-9d69-1f0eb36cb72a.png">

**Comment by ededals** [comment]
What should be the contents of the notification? 
Will simple 
> Session is ready

be sufficient?

**Comment by helfi92** [comment]
Sure, I think that's good :)

**Comment by helfi92** [comment]
Btw, the taskcluster-web repo has moved to  https://github.com/taskcluster/taskcluster/tree/master/ui to be part of the taskcluster monorepo. When you are ready to send a pull-request, feel free to create it there directly since this repository will most likely be archived soon. Let me know if you have questions.

**Comment by ededals** [comment]
Hi, maybe you have something else I could try to solve?

**Comment by helfi92** [comment]
Sure :) I just created https://github.com/taskcluster/taskcluster/issues/208. Please comment there directly if you're interested in tackling this issue.
