### ISSUE TITLE
Create/edit clients

### ISSUE THREAD

**Issue by eliperelman** [taskcluster/taskcluster-web#34]
This view is somewhat synonymous with https://tools.taskcluster.net/auth/clients/email%2Fbastien%40nextcairn.com%2Ftc-notify-test, but should handle new clients with a blank form. I don't want a toggle between view/edit mode. Let's always keep it in edit/form mode.

**Comment by helfi92** [comment]
I have something working locally regarding this issue. I will wait on https://github.com/taskcluster/taskcluster-web/pull/65 to be merged before I open a pull-request for this issue.

**Comment by helfi92** [comment]
Done with https://github.com/taskcluster/taskcluster-web/commit/fb5d3bd006def8b0c3f133de9e2c5864a5931812.
