### ISSUE TITLE
Duplicate function in ViewClients

### ISSUE THREAD

**Issue by arshadkazmi42** [taskcluster/taskcluster-web#340]
There is duplicate `handleCreate` function defined in ViewClients view here
https://github.com/taskcluster/taskcluster-web/blob/master/src/views/Clients/ViewClients/index.jsx#L84-L86
https://github.com/taskcluster/taskcluster-web/blob/master/src/views/Clients/ViewClients/index.jsx#L123-L125

I think this is by mistake and one function should be removed. 
@helfi92 Can you confirm this?

**Comment by helfi92** [comment]
oooo good catch! Indeed, this should be removed.

**Comment by arshadkazmi42** [comment]
Should I create a PR for this? Or we will keep it for `first-timers`?

**Comment by helfi92** [comment]
Your choice :) I've been really happy with all the work you've been doing :) I will label this issue as a "good-first-issue" but feel free to send a PR if you feel like it.

**Comment by arshadkazmi42** [comment]
I think let's leave it for some first-timers to get them on board :+1:
