### ISSUE TITLE
ErrorPanel "X" icon

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#355]
STR:

1. Go to https://github.com/taskcluster/taskcluster-web/blob/master/src/views/Provisioners/ViewProvisioners/index.jsx
2. Add the following code:

```diff
diff --git a/src/views/Provisioners/ViewProvisioners/index.jsx b/src/views/Provisioners/ViewProvisioners/index.jsx
index e20336c..cf2eeb3 100644
--- a/src/views/Provisioners/ViewProvisioners/index.jsx
+++ b/src/views/Provisioners/ViewProvisioners/index.jsx
@@ -24,12 +24,18 @@ export default class ViewProvisioners extends Component {
       description,
       data: { loading, error, provisioners },
     } = this.props;
+    const customError = new Error(`
+    \`\`\`
+    This is a custom error
+    \`\`\`
+    `);
 
     return (
       <Dashboard
         title="Provisioners"
         helpView={<HelpView description={description} />}>
         {loading && <Spinner loading />}
+        <ErrorPanel error={customError} />
         <ErrorPanel error={error} />
         {provisioners && (
           <Grid container spacing={24}>
```
3. Navigate to http://localhost:5080/provisioners

Actual: Hovering on the "X" icon shows a weird hover

![screen shot 2019-01-04 at 10 19 19 am](https://user-images.githubusercontent.com/3766511/50695292-42538d00-100a-11e9-8e2c-a3770043a8fa.png)

Expected: Hovering on the "X" icon does not show a weird hover effect

Inspecting the icon via the dev-tools shows that the button is taking the full height which may be the issue after all:

![screen shot 2019-01-04 at 10 20 45 am](https://user-images.githubusercontent.com/3766511/50695395-85156500-100a-11e9-990a-b4d595fae9e9.png)

Solving this issue will probably require a change in [`@mozilla-frontend-infra/components`](https://github.com/mozilla-frontend-infra/components).

**Comment by ededals** [comment]
Hi, I would like to work on this issue

**Comment by helfi92** [comment]
Go for it :)

**Comment by ededals** [comment]
Hi, 

I did some research today and found that i should modify ErrorPanel of   [@mozilla-frontend-infra/components](https://github.com/mozilla-frontend-infra/components). I think that issue is that `<IconButton>` component is not wrapping its children. 

One issue I have is that I do not know how to make my local changes to  [@mozilla-frontend-infra/components](https://github.com/mozilla-frontend-infra/components) make visible to local taskcluster-web instance. Could you point me in the right direction?

**Comment by helfi92** [comment]
> I think that issue is that <IconButton> component is not wrapping its children

Ah, I think that makes sense :)

> One issue I have is that I do not know how to make my local changes to  [@mozilla-frontend-infra/components](https://github.com/mozilla-frontend-infra/components) make visible to local taskcluster-web instance. Could you point me in the right direction?

You can test your changes directly via`@mozilla-frontend-infra/components`. All you have to do is:

1. Fork and clone https://github.com/mozilla-frontend-infra/components
2. Run `yarn` to install the dependencies
3. Run `yarn start` to start the development server on port 6060
4. Navigate to `http://localhost:6060/#errorpanel`. 
5. Click on "VIEW CODE" to be able to modify the code

![screen shot 2019-01-10 at 7 53 24 am](https://user-images.githubusercontent.com/3766511/50969564-e9be3d00-14ac-11e9-846a-8aa5ad2c03f0.png)

Hope that helps.

**Comment by ededals** [comment]
The solution I came up with is vertically centering the children of `Paper` component and hardcoding the size of `IconButton`

Here is the git diff:

![image](https://user-images.githubusercontent.com/43218607/51054662-348fa000-15e6-11e9-933d-7f260d469c65.png)

And the result: 

![image](https://user-images.githubusercontent.com/43218607/51055017-402f9680-15e7-11e9-9890-1ad9cd54019e.png)

This should work fine as long as nobody increases the size of `CloseIcon`.

Does this solution seem ok to you?

**Comment by helfi92** [comment]
Could you open a pull-requst, please? That way I can pull the code down and test it :)

**Comment by ededals** [comment]
Created a pull request

**Comment by helfi92** [comment]
@ededals the feature was released in `v2.1.1` of `@mozilla-frontend-infra/components`. Did you want to update the package version here?

https://github.com/taskcluster/taskcluster-web/blob/8b7ef495bf01aca4dafbf1b8de560e6b62f1dff9/package.json#L33

I think something like `yarn add @mozilla-frontend-infra/components` would work. Note how we use `yarn` instead of `npm`. This would make sure it updates `yarn.lock`.

**Comment by ededals** [comment]
Hi,
I managed to update the package name locally, but I am having 403 error when trying to push my changes to repository using git: 
![image](https://user-images.githubusercontent.com/43218607/51096649-b5a58d80-17c6-11e9-9b45-82aa215422b9.png)

Do you have any ideas why this could be so?

**Comment by helfi92** [comment]
I suspect you cloned the repository directly without forking it first. You have to first fork and then clone taskcluster-web. `origin` should be pointing to your fork (`git push origin package-update`). Give that a try and let me know how it goes.

**Comment by helfi92** [comment]
The library has been bumped in https://github.com/taskcluster/taskcluster-web/commit/b96b6d175cac14bfbe8cc084f41c4257a6341b53#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R33. We can safely close this issue now. Thank you so much @ededals for your contribution :)

**Comment by ededals** [comment]
Thank you very much for your patience @helfi92 :) Do you have another issue un mind I could work on?

**Comment by helfi92** [comment]
My pleasure. Give me a second, I will create a new issue for you.

**Comment by helfi92** [comment]
Comment on https://github.com/taskcluster/taskcluster-web/issues/371 directly if you would like it to be assigned to you.

**Comment by ededals** [comment]
Great! Thank you
