### ISSUE TITLE
Show a tooltip when hovering on the copy icon

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#358]
STR:

1. Navigate to https://taskcluster-web.netlify.com/tasks/AK5nBLrpRZ-HP4zoXOj3bg
2. Find one of these icons (there's one beside Task Group ID)

<img width="56" alt="screen shot 2019-01-08 at 9 53 09 pm" src="https://user-images.githubusercontent.com/3766511/50873874-d1a4cb80-138f-11e9-84fd-54deb5f70ee4.png">

3. Hover on the icon

Actual: Nothing shows up
Expected: A tooltip shows up showing the text being copied

<img width="226" alt="screen shot 2019-01-08 at 10 05 24 pm" src="https://user-images.githubusercontent.com/3766511/50874318-9905f180-1391-11e9-8b43-d8a5f88bb6f2.png">

Task: Make every `CopyToClipboard` component in the source code use the `title` property in order to show the thing being copied. Here's an example on how to do it for the task group id.

```diff
- <CopyToClipboard text={task.taskGroupId}>
+ <CopyToClipboard title={`${task.taskGroupId} (Copy)`} text={task.taskGroupId}>
```

**Comment by iamsiddhant05** [comment]
I would like to work on this issue.

**Comment by helfi92** [comment]
Go for it :)

**Comment by vivekRaj10** [comment]
Hi @helfi92 , I have analysed this defect & identified the files to be changed. Is it okay if I can work on this one ?

**Comment by helfi92** [comment]
Hi @vivekRaj10. I haven't heard back from @iamsiddhant05 for a week so sure, you can give it a try.
