### ISSUE TITLE
Show Task ID on task screen

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster-web#360]
Use case: I need to run a CLI operation against a task. I'm viewing it (e.g. [here](https://taskcluster-web.netlify.com/tasks/e-vSE19-RQWZiaxeh2BrLQ/runs/0)), and I need to copy and paste the ID to paste into my CLI.

I can see the task group ID, but it would be great if I could see the current task's ID as well

**Comment by helfi92** [comment]
That's a valid use case :) We should add it. One way to do this is to have the search box default to the task ID when navigating to a task.

<img width="509" alt="screen shot 2019-01-10 at 8 12 52 pm" src="https://user-images.githubusercontent.com/3766511/51007086-24a78b80-1514-11e9-8a4d-05558ba9c3f5.png">

**Comment by mitchhentges** [comment]
Hmm, that sounds really useful, but for users who would be seeing this behaviour for the first time, I'm not sure they'll easily realize "ah, maybe my task ID is in the search box"

**Comment by helfi92** [comment]
In that case we can add both under the Task Details tab and the search box :)

**Comment by varundey** [comment]
I would like to take it up since this is very similar to #361 and requires a simple patch. @helfi92 can you let me know if it also requires tests?

**Comment by helfi92** [comment]
@varundey Awesome! Go for it.
