### ISSUE TITLE
Show Task ID in search box

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#361]
STR:

1. Navigate to https://taskcluster-web.netlify.com/tasks/e-vSE19-RQWZiaxeh2BrLQ/runs/0

Actual: The search box has no default value

<img width="524" alt="screen shot 2019-01-10 at 8 11 14 pm" src="https://user-images.githubusercontent.com/3766511/51009549-9553a580-151e-11e9-9ded-5c50cc5f4dd8.png">

Expected: The initial search box state should default to the current task ID

<img width="509" alt="screen shot 2019-01-10 at 8 12 52 pm" src="https://user-images.githubusercontent.com/3766511/51009572-aac8cf80-151e-11e9-94ad-e451f6af983c.png">

Relates to https://github.com/taskcluster/taskcluster-web/issues/360.

**Comment by knrt10** [comment]
@helfi92 I would like to work on this issue.

**Comment by varundey** [comment]
I would like to work on it. Can you give me pointers on where to start from

**Comment by varundey** [comment]
@helfi92 I cloned taskcluster-web-server and spun a local server. After that I tried running setting up the environment and did `npm run start` but I'm getting multiple lint errors in various files. Am I doing something wrong?

**Comment by helfi92** [comment]
> but I'm getting multiple lint errors in various files. Am I doing something wrong?

I'm not sure. Could you provide a screenshot of the linting errors, please?

**Comment by varundey** [comment]
@helfi92 Seems like that was the issue. I tried the same steps with yarn and it is working as expected. Also I tried browsing to https://taskcluster-web.netlify.com/tasks/e-vSE19-RQWZiaxeh2BrLQ/runs/0 after launching both server and web but I am getting lots of console error. Is that expected?
![screen shot 2019-01-14 at 11 28 55 pm](https://user-images.githubusercontent.com/9202135/51130945-4d04f200-1854-11e9-8455-7178dc2e7d93.png)

**Comment by helfi92** [comment]
Yes, that's expected. If you can help us reduce those warnings as well then that would be awesome :) You don't have to do it in this issue however.

**Comment by varundey** [comment]
@helfi92 can I have your mozilla IRC nick? Have some doubts regarding the fix.

**Comment by helfi92** [comment]
Sure, I'm `hassan` on IRC :)

**Comment by helfi92** [comment]
I'll be disconnecting soon for the day but feel free to let me know of your doubts there and I will reply later.
