### ISSUE TITLE
Middle-mouse scroll only goes sideways inconsistently

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster-web#362]
I usually use my middle-mouse scroll ("autoscroll") to zip up and down my log really quickly.
However, sometimes, I middle-mouse click on the logs to move, and it is only moving side-to-side, which is unexpected.

You can reproduce this by going to [this log](https://taskcluster-web.netlify.com/tasks/XHTCM-VRRzCdnzjHPBZTYw/runs/0/logs/https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FXHTCM-VRRzCdnzjHPBZTYw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Fchain_of_trust.log) and trying to middle-mouse-clicked scroll down while stationary.
(note: middle-mouse scrolling _does_ seem to work if you're already scrolling vertically, e.g. by using the mousewheel)

![out](https://user-images.githubusercontent.com/7784737/51014957-0d21d000-151f-11e9-8c83-33c16a35e68e.gif)

**Comment by helfi92** [comment]
Good catch, I can definitely replicate!
