### ISSUE TITLE
Sometimes multiple lines are joined into one, making it harder to parse logs

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster-web#370]
For example, see line `666` (:ghost:) on [this build](https://taskcluster-web.netlify.com/tasks/CQxteRTtQwmsFfVy8_UVNA/runs/0/logs/https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FCQxteRTtQwmsFfVy8_UVNA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L666).

When I do the build locally (`./gradlew assembleFocusX86Nightly`), the output looks like this:

```
warn: removing resource org.mozilla.focus:string/firstrun_defaultbrowser_text2 without required default value.
warn: removing resource org.mozilla.focus:string/preference_autocomplete_user_list_summary without required default value.
warn: removing resource org.mozilla.focus:string/preference_privacy_block_ads_summary without required default value.
warn: removing resource org.mozilla.focus:string/preference_privacy_block_analytics_summary without required default value.
warn: removing resource org.mozilla.focus:string/preference_privacy_block_content_summary2 without required default value.
warn: removing resource org.mozilla.focus:string/preference_privacy_block_social_summary without required default value.
warn: removing resource org.mozilla.focus:string/shortcut_erase_and_open_long_label without required default value.

e: /home/mitch/dev/focus-android/app/src/main/java/org/mozilla/focus/firstrun/FirstrunPagerAdapter.kt: (36, 52): Unresolved reference: firstrun_defaultbrowser_text2

> Task :app:compileFocusX86NightlyKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFocusX86NightlyKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
```

Note that the error ("Unresolved reference") is visible right above where a failure is reported.
When viewing the build in `taskcluster-web`, I need to scroll super far to the right to see the source of the issue

**Comment by helfi92** [comment]
Looking at the [raw output](https://taskcluster-artifacts.net/CQxteRTtQwmsFfVy8_UVNA/0/public/logs/live_backing.log), I see the same issue re: "Unresolved reference" being at the end. The machine where this log is running is probably not interpreting newlines properly.

@djmitche Is this a known issue?

**Comment by djmitche** [comment]
Yeah, basically the task is writing output that would make a nice animation on the console, but in a "log" turns out to be one big, long line.  Most test runners have an option to disable the animations.  Sometimes you can achieve this by piping the output through `cat` (for example, `mocha foo_test,.js | cat`). This makes the test runner's stdout something that is not a tty.

**Comment by mitchhentges** [comment]
Hmm, since it applies to all jobs running through the worker, perhaps something like putting `TERM=dumb` in the environment would be a more apt solution :thinking:

**Comment by djmitche** [comment]
That would just introduce other issues.  Buildbot has dealt with the tty-or-no-tty question for a decade now.  There are no good answers :)

**Comment by helfi92** [comment]
> There are no good answers

Closing for now.
