### ISSUE TITLE
[Hooks] Make sure the owner field is an email

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#371]
STR:

1. Navigate to http://localhost:5080/hooks/taskcluster/azure-backup
2. Change the value under "Owner Email" from `taskcluster-notifications@mozilla.com` to `abc`

Actual: No error hint is shown to the user

Expected: An error is displayed to the user

Here's the [code](https://github.com/taskcluster/taskcluster-web/blob/b96b6d175cac14bfbe8cc084f41c4257a6341b53/src/components/HookForm/index.jsx#L437-L443) you would want to modify. What we want to do is use the `helperText` and the `error` prop to display a hint message whenever the value is not an email. The relevant docs for the `TextField` props can be found [here](https://material-ui.com/api/text-field/#props).

**Comment by ededals** [comment]
I would like to work on this issue

**Comment by helfi92** [comment]
Go for it :)

**Comment by ededals** [comment]
Hi, 
I also added pull request: #396

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster-web/commit/24c197a294fe19a51a2a16628ba20e3c94ff9e8a.

**Comment by ededals** [comment]
Do you have something else I could work on?

**Comment by helfi92** [comment]
Would you like to work on https://github.com/taskcluster/taskcluster-web/issues/273?
