### ISSUE TITLE
Expand hook groups when searching

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster-web#373]
**Summary:**
Hook groups are compressed by default because there's so much content. However, when searching, it's likely that the expanded results of the search will fit on the user's screen. To improve usability, we could expand by default when searching?

**To reproduce:**
1. Go to [hooks](https://taskcluster-web.netlify.com/hooks)
2. Search for `fenix` in the top-right input
3. I need to expand `project-mobile` to view my matching hooks

**Comment by helfi92** [comment]
That's a good idea :) This will need to be done in https://github.com/helfi92/material-ui-treeview. Thanks for bringing that up :)
