### ISSUE TITLE
Hooks: "Last Fired Result" doesn't update until refresh

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster-web#374]
**Summary:**
A common use-case is to fire a hook, then viewed the result. However, I need to refresh my "hook" page before the "Last Fired Result" updates.

**To reproduce:**
1. Open a hook [e.g.: `reference-browser-nightly-staging`](https://taskcluster-web.netlify.com/hooks/project-mobile/reference-browser-nightly-staging)
2. From the bottom-right menu, click "trigger hook"
* "Last Fired Result" link is out-of-date

**Comment by helfi92** [comment]
Many thanks for filing this issue. This needs to be fixed by re-fetching the hook instead of adding a refresh button (1 less click).
