### ISSUE TITLE
Hooks: Refreshing warns "unsaved changes" - even right after saving

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster-web#375]
**Summary:**
Due to #374, I'm commonly refreshing the page. However, every time I refresh, it warns that I have unsaved changes and I have to confirm that I want to refresh the page. This is a bug since, sometimes I don't have unsigned changes, but it still bugs me :)

**To reproduce:**
1. Go to a hook (e.g.: [`reference-browser-nightly-staging`](https://taskcluster-web.netlify.com/hooks/project-mobile/reference-browser-nightly-staging))
2. Use your scrollwheel (this dirties the page?)
3. Refresh your page

**Preferred behaviour:**
* If a field has been edited without the "save" button being pressed yet, then show the "unsaved changes" warning if the user navigates away
* Otherwise, don't show the "unsaved changes" warning

**Comment by helfi92** [comment]
> I'm commonly refreshing the page.

My job is to make sure you don't refresh the page. I believe solving https://github.com/taskcluster/taskcluster-web/issues/374 should make the experience better.

I'll remove the warning but keep it for the shell view when using interactive tasks since `CTRL + W` deletes a word in the terminal and `CMD + W` closes a window on a mac machine :)

**Comment by mitchhentges** [comment]
FWIW, refreshing isn't the only situation where this popped up: sometimes I'd view a hook, not edit anything, then attempt to close the tab - in this scenario, it would bug me with an unnecessary alert. It's a little harder to avoid the "close-a-tab" use-case :wink:

Removing the warning when it's unnecessary, but at least keeping it in interactive shell view sounds :+1:
