### ISSUE TITLE
Hooks: save button appears underneath horizontal scrollbar of task template

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster-web#377]
For example, view [this hook](https://taskcluster-web.netlify.com/hooks/project-mobile/fenix-nightly) in Firefox.

![overlap](https://user-images.githubusercontent.com/7784737/51147011-9716b500-180d-11e9-9581-640453ddd234.jpg)

**Comment by helfi92** [comment]
Ew. Ok let's get this fixed :) Also, thanks for bringing that up. You're the best!
