### ISSUE TITLE
Roles: Unnecessary pagination on-search

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster-web#378]
**Summary:**
Roles are paginated since there's so many. However, it looks like when the results are filtered due to search, the pagination isn't re-calculated. The result is that content that can all fit on one page is still paginated, and it's confusing for the user

**To reproduce:**
Find the Fenix hook's role

1. Go to [roles](https://taskcluster-web.netlify.com/auth/roles)
2. In the top-right search bar, enter "fenix"
* Only two results, neither are the hook's role
3. Note the "next page" arrows on the right, click to the next page
* Now the Fenix hook's role is visible

**Comment by helfi92** [comment]
Regarding pagination, there's not a lot we can do (we use azure tables). We are working on moving things to postgres where I believe this should be fixed. One thing I could do is increase the pagination size window from 20 to 1000. This should help get your result in one page :)

Created https://github.com/taskcluster/taskcluster-web/pull/385.

**Comment by helfi92** [comment]
The experience should now be better. Will consider this "resolved" for now.
