### ISSUE TITLE
Roles: Improve readability of scopes

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster-web#379]
**Summary:**
There's a little more friction to quickly reading and editing a role's scopes in `taskcluster-web`:
* I can't view all the scopes at once: I need to copy-and-paste to an IDE, or keep scrolling up-and-down
* Firefox underlines mispelled words, and most of the words in scopes aren't valid English names. This adds extra noise that I need to filter out when viewing the list of scopes

![screenshot](https://user-images.githubusercontent.com/7784737/51147903-e7434680-1810-11e9-8f71-fda44501eeb2.jpg)

**To reproduce:**
[View a role](https://taskcluster-web.netlify.com/auth/roles/hook-id%3Aproject-mobile%2Ffenix-nightly)

**Preferred Behaviour:**
I'm a pretty big fan of how it looks on the [old tools page](https://tools.taskcluster.net/auth/roles/hook-id%3Aproject-mobile%2Ffenix-nightly) (click "Edit Role") - there's not much noise around the scopes, it's easy to edit, don't need to scroll: :trophy: from me :wink:

**Comment by helfi92** [comment]
Created a PR that will fix this. Many thanks for filing this issue.
