### ISSUE TITLE
Hooks: validate required fields

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster-web#380]
**Summary:**
If I create a hook without a "Hook Group ID", a notification pops up at the top saying "Unknown Server Error". I believe that this error is due to the Hook Group ID being missing

**To reproduce:**
1. Go to [create a new hook](https://taskcluster-web.netlify.com/hooks/create)
2. Enter an ID: "asdf"
3. Enter a name: "asdf"
4. Enter an email: "asdf@asdf.com"
5. Click the save button in the bottom-right

**Preferred behaviour:**
* If any of the required fields are missing content, those specific fields should be highlighted saying that they're missing values

**Comment by helfi92** [comment]
Oh, good catch! This is a bug.

**Comment by helfi92** [comment]
I pushed a patch that would not enable the save button until all required fields have been set. This should be good enough for now. We can revisit the "highlighting" part later if the UX is bad.
