### ISSUE TITLE
Hooks: going back to the hooks list resets my search

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster-web#382]
**Summary:**
Clicking away from the hooks list removes the state the page was in, so that when I click my browser's back button, I'm looking at an unfamiliar, fresh version of the page.

**To reproduce:**
1. Go to [hooks](https://taskcluster-web.netlify.com/hooks)
2. Search for `fenix`
3. Click a hook
4. Click your browser's back button

**Preferred behaviour:**
When the browser's back button is pressed, the following state should be remembered:
* Expanded hook groups
* The current search

**Comment by helfi92** [comment]
Good idea. We should use a query parameter `?search=...` which will be used to filter the list.

**Comment by OjaswinM** [comment]
Hey @helfi92, I can take this up if it's okay?

**Comment by helfi92** [comment]
Go for it :)
