### ISSUE TITLE
Sort roles list by ID

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster-web#388]
**Summary:**
A common use-case is to search by product, then edit one or two roles (e.g.: a nightly hook's role + a staging nightly hook's role). However, right now, the roles aren't close to others of the same type: they're in a bit of a random order, which makes editing all `$product` roles of a certain type a little tougher

**To reproduce:**
1. Go to [roles](https://taskcluster-web.netlify.com/auth/roles)
2. Search for "Focus"
3. Find all hooks for focus

**Preferred behaviour:**
Perhaps sort by Role ID?

**Comment by helfi92** [comment]
Clicking on the header should be able to sort the list by IDs.

![screen shot 2019-01-15 at 1 17 52 pm](https://user-images.githubusercontent.com/3766511/51200629-0e108400-18c8-11e9-8ba4-42c19cff4210.png)

**Comment by helfi92** [comment]
We can probably make that the default sort. I'll send a patch.
