### ISSUE TITLE
Show task status in favicon

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster-web#393]
**Summary:**
On the old Taskcluster UI, the favicon would have a little circle with a colour representing progress, e.g.:
* Green for success
* Yellow for in-progress
* Red for failed

This improves the use-case where I have multiple tabs with builds, but I want to be able to tell when they fail/succeed at-a-glance.

**To reproduce:**
1. Open a [task](https://taskcluster-web.netlify.com/tasks/Bs9vIsq8QzigKhfG5wHWzw)

**Comment by helfi92** [comment]
Good catch. We have integrate this functionality in the groups UI but must have forgotten to include it in the task view.
