### ISSUE TITLE
Hooks: All buttons are disabled on-save

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster-web#402]
**Summary:**
All buttons are disabled while a save is in-progress. This means that if I want to save and trigger a hook, I can't just click-click: I have to wait for the save to complete.

(sorry for the white lines here, my compositor or something is misbehaving. /me shakes fist)
![out](https://user-images.githubusercontent.com/7784737/51351008-83ae5880-1a5e-11e9-92be-3881c83ad3b4.gif)

**To reproduce:**
1. Go to [a hook](https://taskcluster-web.netlify.com/hooks/project-mobile/reference-browser-nightly-staging)
2. Click save, then immediately hover over the actions
3. The actions buttons are disabled until the save finishes

**Preferred behaviour:**
You could allow users to press the action buttons, but just delay the actual request until the save finishes? :thinking: There might be easier alternatives

**Comment by helfi92** [comment]
I think this will add complexity to the code. Has it been affecting your experience/productivity? The current flow will also make sure the user is not confused as to whether it triggered the old/updated hook.

**Comment by mitchhentges** [comment]
That's true, this could add significant complexity for the payoff - this doesn't affect my productivity significantly, so it's a :man_shrugging: 

> make sure the user is not confused as to whether it triggered the old/updated hook.

True, though I would guess that this shakes out as follows:
* Cautious users wait until the save finishes, then press the button. The triggered task uses post-edit v alues, these users are content.
* Adventurous users press save immediately. When the triggered task uses the post-edit values, these users learn that they're able to click immediately. These guys are content.

-----

Honestly, yeah, the save is really quick, so this is hardly that big of a deal. It's a potential micro-optimization, but unless the save gets slower, it's not really a concern :smile:

**Comment by helfi92** [comment]
Sounds good. I guess we can revisit if the save gets slower :) Thanks again for raising the issue.
