### ISSUE TITLE
Worker types view modal not opening

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#409]
STR:

1. Navigate to https://taskcluster-web.netlify.com/provisioners/aws-provisioner-v1
2. Click on any info icon

![screen shot 2019-01-22 at 2 38 59 pm](https://user-images.githubusercontent.com/3766511/51560763-7aa0fb00-1e53-11e9-8ce9-07266c668ca8.png)

Expected: A drawer is opened from the right

Actual: Nothing shows up. There is an error in the console:

![screen shot 2019-01-22 at 2 39 39 pm](https://user-images.githubusercontent.com/3766511/51560807-92787f00-1e53-11e9-8297-1f5b973ed90d.png)

**Comment by ededals** [comment]
I will work on this issue.

**Comment by helfi92** [comment]
Go for it.

**Comment by ededals** [comment]
@helfi92 what could I work on next?

**Comment by helfi92** [comment]
Do you want to work on https://github.com/taskcluster/taskcluster-web/issues/332?
