### ISSUE TITLE
Pulse messages

### ISSUE THREAD

**Issue by eliperelman** [taskcluster/taskcluster-web#41]
This view is synonymous with https://tools.taskcluster.net/pulse-inspector. This should utilize the GraphQL message subscription available on the top-level `Subscription`.

**Comment by helfi92** [comment]
We currently have a GSOC student working on rewriting taskcluster-events to use server-sent events for pulse communication instead of websockets. We'll probably need to modify the tc-web-server to reflect the new change once it lands.

**Comment by eliperelman** [comment]
No, we use subscriptions directly to pulse and do not use events on the server.

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster-web/commit/57314ffb5afd8ebbc1de264a726a379cb781a495. The actual listening for pulse messages is still not implemented though. Simply the UI part is done.

Blocker: https://github.com/taskcluster/taskcluster-web/issues/94
