### ISSUE TITLE
Logs are empty

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster-web#410]
~All logs are currently five empty lines~
~For example, [this log](https://taskcluster-web.netlify.com/tasks/cKhZgaC9QzSzC9MjNrG5bw/runs/0/logs/https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FcKhZgaC9QzSzC9MjNrG5bw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log)~

Hmm, my build was finished, but the log was empty. It's been a couple minutes, but now it's populated.
:thinking: it's working, not sure what I ran into

**Comment by mitchhentges** [comment]
I ran into a strange delay where the three builds I just ran were all marked green, but the logs just had five lines. However, a couple minutes later, the logs are now populated.
Thinking about this further, this behaviour is probably the same as it was before, but since the logs aren't fully empty (there's five blank lines) it threw me off? Not sure, but this bug isn't valid :)

**Comment by helfi92** [comment]
> there's five blank lines

We added 5 extra lines at the end of the log to make space for the action buttons at the bottom. There used to be 1 in the past.

**Comment by mitchhentges** [comment]
Yeah, we're on the same page here. I'm not sure if I'm stumbling on an intermittent issue where logs don't load, or if I'm getting used to the 5-empty-line behaviour. This is entirely safe to disregard in the meantime, sorry for unnecessary issue spam :)
