### ISSUE TITLE
Cache purges list

### ISSUE THREAD

**Issue by eliperelman** [taskcluster/taskcluster-web#42]
This view is synonymous with https://tools.taskcluster.net/purge-caches. The view layout should be the list, with a button to start a new cache purge. The cache purge form should not be always visible; instead we could probably use a dialog form when clicking the button.

**Comment by helfi92** [comment]
@eliperelman To stay consistent with the other views, I think the form should be in a new page `/purge-caches/create` instead of a dialog. Let me know if you don't agree.

**Comment by eliperelman** [comment]
I agree.
