### ISSUE TITLE
Unauthenticated landing page

### ISSUE THREAD

**Issue by eliperelman** [taskcluster/taskcluster-web#49]
This is the view that is rendered when visiting `/` when **not** logged in. The point of this page will be mostly informational in nature, encouraging the visitor to log in.

**Comment by helfi92** [comment]
![screen shot 2018-08-29 at 12 28 50 pm](https://user-images.githubusercontent.com/3766511/44801464-2422df80-ab87-11e8-83d1-abf3298f7568.png)
