### ISSUE TITLE
Global search

### ISSUE THREAD

**Issue by eliperelman** [taskcluster/taskcluster-web#57]
The individual search boxes in each view are only meant to search for the parameters necessary to render that view, and are duplicated in every view. Let's create a global search component that goes into the app bar, and can search across many types: tasks, task groups, docs, and more. This can be pattern-based, so a string matching a task ID could show an autocomplete to link to either a task or a task group, etc.

**Comment by helfi92** [comment]
Each view now has their search component embedded in the app bar. Previously (referring to the tools site), navigating between microservices would require the user to go to the homepage and then select and different microservice. Now that the navigation is fixed on the left, the user is most of the time away one click away from their view. That said, I don't think we should worry about global search just yet.
