### ISSUE TITLE
Remove ramda's memoize function and use fast-memoize instead

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#90]
The numbers shown in https://github.com/caiogondim/fast-memoize.js for fast-memoize are far more performant than ramda's memoize function.

**Comment by korina0430** [comment]
Hi! I'd like to start working on this. What files need this function replaced?

**Comment by helfi92** [comment]
Hi @korina0430, this is awesome :) Any [place where we use](https://github.com/taskcluster/taskcluster-web/search?q=memoizeWith&unscoped_q=memoizeWith) `memoizeWith` will need to be changed to the `memoize` function from the `fast-memoize` library. Here's an [example](https://github.com/taskcluster/taskcluster-web/blob/f64569c7ecb052d438f5ae67a029ac771aa5486b/src/components/AwsProvisionerErrorsTable/index.jsx#L48-L72) of a place in the code where we use the new fast-memoize library.

Feel free to change one function then send a pull-request for me to look at. Once we agree on the solution you can take care of the other functions. I'm here to help so feel free to ask questions after investigating.

**Comment by korina0430** [comment]
Hi @helfi92 
Sorry for the delayed response! Next week I will have more time to work on/ finish this bug. For starters, I'm confused as to where we import the new fast-memoize library in the cases of when memoize() is called in non-js files. For example mozilla-source\mozilla-central\python\mozbuild\mozbuild\action\check_binary.py contains the memoize() function but it looks explicitly defined in a util.py file. 

Secondly, I took a look at the example you posted (thanks for posting that btw!), and I don't have the taskcluster-web directory on my local Mozilla build. I only have taskcluster...

**Comment by korina0430** [comment]
One more question- when I use searchFox to find memoizeWith it comes back with no results.

**Comment by helfi92** [comment]
Have you tried searching the taskcluster-web repo? https://github.com/taskcluster/taskcluster-web/search?q=memoizeWith&unscoped_q=memoizeWith

**Comment by helfi92** [comment]
> Next week I will have more time to work on/ finish this bug

Sounds good, I'm here to help if you have questions.

**Comment by korina0430** [comment]
I just clicked the link you posted and I see the function memoizeWith now. Can you clarify the difference between this repo and the mozilla-source. How come I can't find the taskcluster-web-repo inside mozilla-source?  I'm very new to open source!

Just to clarify: 
In order to make changes to this repo, do I still use mercurial to create a patch file and then upload that patch file here?

**Comment by helfi92** [comment]
taskcluster-web is not part of the firefox source code. It's a website that lives outside of firefox. To answer your question, we don't use mercurial to creates patches for taskcluster-web. We use git.
