### ISSUE TITLE
Sign in menu

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster-web#98]
Clicking on the sign menu then clicking away doesn't close the menu unless a selection is picked. We should fix that.

**Comment by sonakshisaxena1** [comment]
@helfi92 I would like to try this.

**Comment by helfi92** [comment]
Awesome! Go for it.`taskcluster-web` uses components from https://material-ui-next.com/ for its UI components. Let me know if you have any questions.

**Comment by sonakshisaxena1** [comment]
I am facing issues in setting up the environment. 
In the following - 
```
APPLICATION_NAME="Taskcluster"
AUTH0_DOMAIN="auth.mozilla.auth0.com"
AUTH0_CLIENT_ID="29t2n3LKKnyTbGtWmfTkQpau0mp7QmMH"
AUTH0_REDIRECT_URI="http://localhost:5080/login"
AUTH0_RESPONSE_TYPE="token id_token"
AUTH0_SCOPE="openid profile"
PORT="5080"
```
The only thing that needs to be replaced is - `"token id_token"` right?

**Comment by helfi92** [comment]
Try adding `LOGIN_STRATEGIES="github"`.

**Comment by sonakshisaxena1** [comment]
Okay. That worked!
But how should get past the sign in process?

**Comment by helfi92** [comment]
Click "Sign In", then "Sign in with credentials". Type anything for the client ID and access token and then click on "Sign In".

**Comment by sonakshisaxena1** [comment]
Got through that. Just one last thing, the main website is: https://tools.taskcluster.net/ right? 
Cause it looks different locally.

**Comment by helfi92** [comment]
Not quite. This site is not deployed yet. Once most issues are resolved, it will be a replacement for  https://tools.taskcluster.net. We are almost there.

**Comment by helfi92** [comment]
It is a rewrite of taskcluster-tools.

**Comment by sonakshisaxena1** [comment]
Oh, gotcha. Thanks!

**Comment by helfi92** [comment]
No worries :)

**Comment by sonakshisaxena1** [comment]
@helfi92 I am stuck in this. I tried passing a function, suppose, `handleClose` (where I passed false through `open` prop as well as tried changing a state by setting one manually) in `onClose` but instead of solving, the dialog stops getting closed on pressing the "Esc" key too. 

Further, we are using **Simple Dialog** and as per https://material-ui.com/demos/dialogs/ , it should automatically close the dialog on pressing the Esc key or on clicking outside the modal, but the latter isn't happening. 
Can you help me find my mistake?

**Comment by helfi92** [comment]
```jsx
<Menu
  id="user-menu"
  anchorEl={anchorEl}
  open={Boolean(anchorEl)}
  onClose={this.handleClose}>
  // ...
</Menu>
```

When the user clicks away or presses the `ESC` key, it is trying to call the `onClose` handle but the function we are telling it to trigger `handleClose` does not exist. I think the solution is to rename `handleClose` to `handleMenuClose`. Let me know if that works.

**Comment by sonakshisaxena1** [comment]
Yes, it does.
I'll make a commit regarding this. Thankyou :)

**Comment by helfi92** [comment]
Fixed in https://github.com/taskcluster/taskcluster-web/commit/a157cde338a605fa07dff114383e116abdc50687.
